import { AppShell } from "@/components/AppShell";
import { WorkspaceAccess } from "@/components/WorkspaceAccess";
import { TemplateVisual } from "@/components/TemplateVisual";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { type TemplateCategory } from "@shared/appBuilderCatalog";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ChevronLeft, ChevronRight, FileImage, FolderPlus, GripVertical, ImagePlus, Layers3, Loader2, MonitorSmartphone, PanelRightOpen, Pencil, Plus, Save, Settings2, Trash2, Upload, X } from "lucide-react";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";

const labels: Record<TemplateCategory, { ar: string; en: string }> = {
  ecommerce: { ar: "متجر إلكتروني", en: "E-commerce" }, education: { ar: "تطبيق تعليمي", en: "Education" }, games: { ar: "تطبيق ألعاب", en: "Games" }, music: { ar: "تطبيق موسيقى", en: "Music" }, podcasts: { ar: "تطبيق بودكاست", en: "Podcasts" }, movies: { ar: "أفلام ومسلسلات", en: "Movies & shows" }, services: { ar: "تطبيق خدمات", en: "Services" },
};

const componentTypeLabels: Record<string, { ar: string; en: string }> = {
  Card: { ar: "بطاقة", en: "Card" }, Button: { ar: "زر", en: "Button" }, List: { ar: "قائمة", en: "List" }, Image: { ar: "صورة", en: "Image" }, Video: { ar: "فيديو", en: "Video" }, Form: { ar: "نموذج", en: "Form" },
};

const componentTypes = Object.keys(componentTypeLabels);

function BuilderShell({ children }: { children: React.ReactNode }) { return <AppShell><WorkspaceAccess>{children}</WorkspaceAccess></AppShell>; }

function getQueryTemplateId() {
  const value = new URLSearchParams(window.location.search).get("template");
  return value ? Number(value) : undefined;
}

export function CreateProjectPage() {
  const { copy, isArabic } = useLocale();
  const [, setLocation] = useLocation();
  const localUser = trpc.localAuth.me.useQuery();
  const isAuthenticated = Boolean(localUser.data);
  const templates = trpc.appBuilder.templates.list.useQuery();
  const create = trpc.appBuilder.projects.create.useMutation({ onSuccess: ({ id }) => setLocation(`/editor/${id}`) });
  const [templateId, setTemplateId] = useState<number | undefined>(getQueryTemplateId());
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [packageName, setPackageName] = useState("");
  const [language, setLanguage] = useState<"ar" | "en" | "both">("both");
  const selected = templates.data?.find(template => template.id === templateId);

  useEffect(() => { if (!templateId && templates.data?.[0]) setTemplateId(templates.data[0].id); }, [templateId, templates.data]);
  function submit(event: FormEvent) {
    event.preventDefault();
    if (!selected || !isAuthenticated) return;
    create.mutate({ name, description: description || undefined, packageName: packageName || undefined, category: selected.category as TemplateCategory, templateId: selected.id, language });
  }
  return <BuilderShell><div className="builder-heading"><div><Link href="/templates" className="back-link">{isArabic ? <ArrowRight /> : <ArrowLeft />}{copy("العودة للقوالب", "Back to templates")}</Link><p className="section-kicker mt-5">{copy("مشروع جديد", "NEW PROJECT")}</p><h1>{copy("أنشئ تطبيقك من قالب", "Create your app from a template")}</h1><p>{copy("اختر القالب، ثم أعط مشروعك اسمًا وانطلق إلى المحرر.", "Choose a template, name your project, and move directly into the editor.")}</p></div></div>
    <div className="create-layout"><form className="workspace-panel create-form" onSubmit={submit}><div className="form-section-title"><span>01</span><div><h2>{copy("بيانات المشروع", "Project details")}</h2><p>{copy("يمكنك تعديل هذه البيانات لاحقًا من الإعدادات.", "You can update these details later from settings.")}</p></div></div><div className="space-y-2"><Label>{copy("اسم المشروع", "Project name")}</Label><Input value={name} onChange={event => setName(event.target.value)} required minLength={2} placeholder={copy("مثال: متجري الإلكتروني", "Example: My online store")} /></div><div className="space-y-2"><Label>{copy("وصف مختصر", "Short description")}</Label><Textarea value={description} onChange={event => setDescription(event.target.value)} placeholder={copy("ما الفكرة التي سيخدمها تطبيقك؟", "What idea will your app serve?")} /></div><div className="form-split"><div className="space-y-2"><Label>{copy("اسم الحزمة", "Package name")}</Label><Input dir="ltr" value={packageName} onChange={event => setPackageName(event.target.value)} placeholder="com.company.app" /></div><div className="space-y-2"><Label>{copy("لغة التطبيق", "App language")}</Label><div className="segment-control"><button type="button" className={language === "ar" ? "selected" : ""} onClick={() => setLanguage("ar")}>العربية</button><button type="button" className={language === "en" ? "selected" : ""} onClick={() => setLanguage("en")}>English</button><button type="button" className={language === "both" ? "selected" : ""} onClick={() => setLanguage("both")}>{copy("كلاهما", "Both")}</button></div></div></div>
      {create.error && <p className="form-error">{copy("تعذر إنشاء المشروع. سجّل الدخول أولًا ثم أعد المحاولة.", "Could not create the project. Sign in first and try again.")}</p>}{!isAuthenticated && <div className="signin-warning"><p>{copy("يلزم تسجيل الدخول لحفظ مشروعك في حسابك.", "Sign in is required to save a project to your account.")}</p><Link href="/auth"><Button type="button" variant="outline">{copy("تسجيل الدخول", "Sign in")}</Button></Link></div>}<Button type="submit" disabled={!isAuthenticated || create.isPending || !selected || name.trim().length < 2} className="workspace-primary create-submit">{create.isPending ? <Loader2 className="animate-spin" /> : <Plus />}{copy("إنشاء المشروع وفتح المحرر", "Create project & open editor")}</Button></form>
      <aside className="workspace-panel template-picker"><div className="form-section-title"><span>02</span><div><h2>{copy("اختر قالبًا", "Choose a template")}</h2><p>{copy("سيُنشأ هيكل صفحات مقترح تلقائيًا.", "A suggested page structure is created automatically.")}</p></div></div>{templates.isLoading ? <div className="picker-loading"><Loader2 className="animate-spin" /></div> : <div className="picker-list">{templates.data?.map(template => <button type="button" key={template.id} onClick={() => setTemplateId(template.id)} className={cn("picker-item", selected?.id === template.id && "picker-item-active")}><TemplateVisual size="small" iconName={template.iconName} color={template.accentColor} /><div><strong>{isArabic ? template.nameAr : template.nameEn}</strong><span>{labels[template.category as TemplateCategory][isArabic ? "ar" : "en"]}</span></div>{selected?.id === template.id && <span className="picker-check">✓</span>}</button>)}</div>}</aside></div>
  </BuilderShell>;
}

function ComponentsPreview({ components, isArabic }: { components: Array<{ id: number; componentType: string; labelAr: string; labelEn: string }>; isArabic: boolean }) {
  if (!components.length) return <div className="preview-empty"><Layers3 /><span>{isArabic ? "أضف مكونات لهذه الصفحة" : "Add components to this page"}</span></div>;
  return <div className="preview-component-stack">{components.map((component, index) => <div key={component.id} className={cn("preview-component", index === 0 && "preview-component-featured")}><span>{componentTypeLabels[component.componentType]?.[isArabic ? "ar" : "en"] ?? component.componentType}</span><strong>{isArabic ? component.labelAr : component.labelEn}</strong></div>)}</div>;
}

export function EditorPage() {
  const { copy, isArabic } = useLocale();
  const [, params] = useRoute("/editor/:id");
  const projectId = Number(params?.id);
  const workspace = trpc.appBuilder.projects.getWorkspace.useQuery(projectId, { enabled: Number.isFinite(projectId), retry: false });
  const utils = trpc.useUtils();
  const [activePageId, setActivePageId] = useState<number | null>(null);
  const [newPage, setNewPage] = useState(false);
  const [pageAr, setPageAr] = useState("");
  const [pageEn, setPageEn] = useState("");
  const [componentAr, setComponentAr] = useState("");
  const [componentEn, setComponentEn] = useState("");
  const [componentType, setComponentType] = useState("Card");
  const [assetMessage, setAssetMessage] = useState("");
  const [editingPage, setEditingPage] = useState<{ id: number; titleAr: string; titleEn: string; route: string } | null>(null);
  const [editingComponent, setEditingComponent] = useState<{ id: number; componentType: string; labelAr: string; labelEn: string } | null>(null);
  const invalidate = () => utils.appBuilder.projects.getWorkspace.invalidate(projectId);
  const addPage = trpc.appBuilder.editor.addPage.useMutation({ onSuccess: () => { setNewPage(false); setPageAr(""); setPageEn(""); invalidate(); } });
  const deletePage = trpc.appBuilder.editor.deletePage.useMutation({ onSuccess: invalidate });
  const updatePage = trpc.appBuilder.editor.updatePage.useMutation({ onSuccess: invalidate });
  const addComponent = trpc.appBuilder.editor.addComponent.useMutation({ onSuccess: () => { setComponentAr(""); setComponentEn(""); invalidate(); } });
  const updateComponent = trpc.appBuilder.editor.updateComponent.useMutation({ onSuccess: invalidate });
  const reorderComponents = trpc.appBuilder.editor.reorderComponents.useMutation({ onSuccess: invalidate });
  const deleteComponent = trpc.appBuilder.editor.deleteComponent.useMutation({ onSuccess: invalidate });
  const uploadAsset = trpc.appBuilder.assets.upload.useMutation({ onSuccess: () => setAssetMessage(copy("تم رفع الأصل بنجاح", "Asset uploaded successfully")), onError: () => setAssetMessage(copy("تعذر رفع الملف", "Could not upload the file")) });
  const assets = trpc.appBuilder.assets.list.useQuery(projectId, { enabled: Number.isFinite(projectId), retry: false });
  const reorderPages = trpc.appBuilder.editor.reorderPages.useMutation({ onSuccess: invalidate });
  const pages = workspace.data?.pages ?? [];
  const activePage = pages.find(page => page.id === activePageId) ?? pages[0];
  const pageComponents = workspace.data?.components.filter(component => component.pageId === activePage?.id) ?? [];
  useEffect(() => { if (!activePageId && pages[0]) setActivePageId(pages[0].id); }, [activePageId, pages]);
  function handleAsset(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !projectId) return; const reader = new FileReader(); reader.onload = () => { const data = String(reader.result).split(",")[1]; if (data) uploadAsset.mutate({ projectId, filename: file.name, mimeType: file.type || "application/octet-stream", kind: file.type.startsWith("image/") ? "image" : "other", dataBase64: data }); }; reader.readAsDataURL(file); }
  function movePage(pageId: number, direction: -1 | 1) { const index = pages.findIndex(page => page.id === pageId); const target = index + direction; if (index < 0 || target < 0 || target >= pages.length) return; const reordered = [...pages]; [reordered[index], reordered[target]] = [reordered[target], reordered[index]]; reorderPages.mutate({ projectId, pageIds: reordered.map(page => page.id) }); }
  function moveComponent(componentId: number, direction: -1 | 1) { if (!activePage) return; const index = pageComponents.findIndex(component => component.id === componentId); const target = index + direction; if (index < 0 || target < 0 || target >= pageComponents.length) return; const reordered = [...pageComponents]; [reordered[index], reordered[target]] = [reordered[target], reordered[index]]; reorderComponents.mutate({ projectId, pageId: activePage.id, componentIds: reordered.map(component => component.id) }); }
  function editPage(page: typeof pages[number]) { setEditingPage({ id: page.id, titleAr: page.titleAr, titleEn: page.titleEn, route: page.route }); }
  function editComponent(component: typeof pageComponents[number]) { setEditingComponent({ id: component.id, componentType: component.componentType, labelAr: component.labelAr, labelEn: component.labelEn }); }
  if (workspace.isLoading) return <BuilderShell><div className="editor-loading"><Loader2 className="animate-spin" />{copy("يتم تحميل المحرر…", "Loading editor…")}</div></BuilderShell>;
  if (!workspace.data) return <BuilderShell><div className="editor-error"><FolderPlus /><h1>{copy("المشروع غير متاح", "Project unavailable")}</h1><p>{copy("سجّل الدخول ثم أنشئ مشروعًا جديدًا لفتح المحرر.", "Sign in and create a project to open the editor.")}</p><Link href="/create"><Button className="workspace-primary">{copy("إنشاء مشروع", "Create project")}</Button></Link></div></BuilderShell>;
  return <BuilderShell><div className="editor-topline"><div><Link href="/projects" className="back-link">{isArabic ? <ArrowRight /> : <ArrowLeft />}{copy("مشاريعي", "My projects")}</Link><div className="editor-project-title"><span className="section-kicker">{labels[workspace.data.project.category as TemplateCategory]?.[isArabic ? "ar" : "en"]}</span><h1>{workspace.data.project.name}</h1></div></div><div className="editor-actions"><label className="asset-upload"><ImagePlus />{copy("رفع أصل", "Upload asset")}<input type="file" accept="image/*,.ttf,.otf,.pdf" onChange={handleAsset} /></label><Button variant="outline"><MonitorSmartphone />{copy("معاينة", "Preview")}</Button><Button className="workspace-primary"><Save />{copy("حفظ", "Save")}</Button></div></div>{assetMessage && <div className="asset-message">{assetMessage}<button onClick={() => setAssetMessage("")}><X /></button></div>}
    <div className="editor-layout"><aside className="editor-pages workspace-panel"><div className="editor-panel-heading"><div><h2>{copy("صفحات التطبيق", "App pages")}</h2><span>{pages.length}</span></div><button onClick={() => setNewPage(true)}><Plus /></button></div><div className="page-nav-list">{pages.map((page, index) => <div className={cn("page-nav-item", activePage?.id === page.id && "page-nav-item-active")} key={page.id}><button onClick={() => setActivePageId(page.id)}><GripVertical /><span>{isArabic ? page.titleAr : page.titleEn}</span></button><div className="page-nav-actions"><button className="page-move" onClick={() => editPage(page)} aria-label={copy("تعديل الصفحة", "Edit page")}><Pencil /></button><button className="page-move" disabled={index === 0 || reorderPages.isPending} onClick={() => movePage(page.id, -1)} aria-label={copy("نقل الصفحة للأعلى", "Move page up")}><ArrowUp /></button><button className="page-move" disabled={index === pages.length - 1 || reorderPages.isPending} onClick={() => movePage(page.id, 1)} aria-label={copy("نقل الصفحة للأسفل", "Move page down")}><ArrowDown /></button><button className="delete-mini" onClick={() => deletePage.mutate({ projectId, pageId: page.id })} aria-label={copy("حذف الصفحة", "Delete page")}><Trash2 /></button></div></div>)}</div>{newPage && <form className="inline-form" onSubmit={event => { event.preventDefault(); addPage.mutate({ projectId, titleAr: pageAr, titleEn: pageEn, route: `/${pageEn.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-") || "page"}` }); }}><Input value={pageAr} onChange={event => setPageAr(event.target.value)} placeholder={copy("عنوان عربي", "Arabic title")} required /><Input value={pageEn} onChange={event => setPageEn(event.target.value)} placeholder={copy("عنوان إنجليزي", "English title")} required /><div><Button size="sm" type="submit">{copy("إضافة", "Add")}</Button><Button size="sm" type="button" variant="ghost" onClick={() => setNewPage(false)}>{copy("إلغاء", "Cancel")}</Button></div></form>}</aside>
      <section className="editor-canvas workspace-panel"><div className="canvas-toolbar"><div><span>{copy("معاينة مباشرة", "Live preview")}</span><strong>{isArabic ? activePage?.titleAr : activePage?.titleEn}</strong></div><div className="device-tabs"><button className="active">{copy("جوال", "Mobile")}</button><button>{copy("لوحي", "Tablet")}</button></div></div><div className="phone-frame"><div className="phone-notch" /><div className="phone-appbar"><span className="phone-logo" /><strong>{isArabic ? activePage?.titleAr : activePage?.titleEn}</strong><span>•••</span></div><div className="phone-content"><h3>{isArabic ? activePage?.titleAr : activePage?.titleEn}</h3><p>{copy("هذه معاينة بنية الصفحة والمكونات التي تضيفها.", "This previews the page structure and components you add.")}</p><ComponentsPreview components={pageComponents} isArabic={isArabic} /></div><div className="phone-bottom"><i /><i className="active" /><i /></div></div></section>
      <aside className="editor-properties workspace-panel"><div className="editor-panel-heading"><div><h2>{copy("المكونات", "Components")}</h2><span>{pageComponents.length}</span></div><PanelRightOpen /></div><form className="component-form" onSubmit={event => { event.preventDefault(); if (!activePage) return; addComponent.mutate({ projectId, pageId: activePage.id, componentType, labelAr: componentAr, labelEn: componentEn }); }}><Label>{copy("نوع المكون", "Component type")}</Label><select value={componentType} onChange={event => setComponentType(event.target.value)}>{componentTypes.map(type => <option key={type} value={type}>{componentTypeLabels[type][isArabic ? "ar" : "en"]}</option>)}</select><Input value={componentAr} onChange={event => setComponentAr(event.target.value)} placeholder={copy("اسم المكون بالعربية", "Arabic label")} required /><Input value={componentEn} onChange={event => setComponentEn(event.target.value)} placeholder={copy("اسم المكون بالإنجليزية", "English label")} required /><Button type="submit" variant="outline"><Plus />{copy("إضافة مكون", "Add component")}</Button></form><div className="component-list">{pageComponents.map((component, index) => <div key={component.id} className="component-list-item"><div><span>{componentTypeLabels[component.componentType]?.[isArabic ? "ar" : "en"] ?? component.componentType}</span><strong>{isArabic ? component.labelAr : component.labelEn}</strong></div><div className="component-row-actions"><button disabled={index === 0 || reorderComponents.isPending} onClick={() => moveComponent(component.id, -1)} aria-label={copy("نقل المكون للأعلى", "Move component up")}><ArrowUp /></button><button disabled={index === pageComponents.length - 1 || reorderComponents.isPending} onClick={() => moveComponent(component.id, 1)} aria-label={copy("نقل المكون للأسفل", "Move component down")}><ArrowDown /></button><button onClick={() => editComponent(component)} aria-label={copy("تعديل المكون", "Edit component")}><Pencil /></button><button onClick={() => deleteComponent.mutate({ projectId, componentId: component.id })} aria-label={copy("حذف المكون", "Delete component")}><Trash2 /></button></div></div>)}</div><div className="editor-assets"><div className="editor-assets-heading"><FileImage /><span>{copy("الأصول المرفوعة", "Uploaded assets")}</span></div>{assets.isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : assets.data?.length ? <div className="asset-list">{assets.data.map(asset => <a href={asset.url} target="_blank" rel="noreferrer" key={asset.id} className="asset-list-item"><ImagePlus /><span>{asset.filename}</span></a>)}</div> : <p>{copy("لم ترفع أي أصول بعد.", "No assets uploaded yet.")}</p>}</div></aside></div>
    <Dialog open={Boolean(editingPage)} onOpenChange={open => { if (!open) setEditingPage(null); }}><DialogContent dir={isArabic ? "rtl" : "ltr"}><DialogHeader><DialogTitle>{copy("تعديل الصفحة", "Edit page")}</DialogTitle><DialogDescription>{copy("حدّث أسماء الصفحة ومسارها داخل التطبيق.", "Update the page names and its route in the app.")}</DialogDescription></DialogHeader>{editingPage && <form className="space-y-4" onSubmit={event => { event.preventDefault(); updatePage.mutate({ projectId, pageId: editingPage.id, titleAr: editingPage.titleAr, titleEn: editingPage.titleEn, route: editingPage.route }); setEditingPage(null); }}><div className="space-y-2"><Label>{copy("العنوان بالعربية", "Arabic title")}</Label><Input value={editingPage.titleAr} required onChange={event => setEditingPage({ ...editingPage, titleAr: event.target.value })} /></div><div className="space-y-2"><Label>{copy("العنوان بالإنجليزية", "English title")}</Label><Input value={editingPage.titleEn} required onChange={event => setEditingPage({ ...editingPage, titleEn: event.target.value })} /></div><div className="space-y-2"><Label>{copy("المسار", "Route")}</Label><Input dir="ltr" value={editingPage.route} required onChange={event => setEditingPage({ ...editingPage, route: event.target.value })} /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setEditingPage(null)}>{copy("إلغاء", "Cancel")}</Button><Button className="workspace-primary" type="submit">{copy("حفظ التغييرات", "Save changes")}</Button></DialogFooter></form>}</DialogContent></Dialog>
    <Dialog open={Boolean(editingComponent)} onOpenChange={open => { if (!open) setEditingComponent(null); }}><DialogContent dir={isArabic ? "rtl" : "ltr"}><DialogHeader><DialogTitle>{copy("تعديل المكون", "Edit component")}</DialogTitle><DialogDescription>{copy("عدّل نوع المكون واسمه في اللغتين.", "Update the component type and its labels in both languages.")}</DialogDescription></DialogHeader>{editingComponent && <form className="space-y-4" onSubmit={event => { event.preventDefault(); updateComponent.mutate({ projectId, componentId: editingComponent.id, componentType: editingComponent.componentType, labelAr: editingComponent.labelAr, labelEn: editingComponent.labelEn }); setEditingComponent(null); }}><div className="space-y-2"><Label>{copy("نوع المكون", "Component type")}</Label><select className="editor-select" value={editingComponent.componentType} onChange={event => setEditingComponent({ ...editingComponent, componentType: event.target.value })}>{componentTypes.map(type => <option key={type} value={type}>{componentTypeLabels[type][isArabic ? "ar" : "en"]}</option>)}</select></div><div className="space-y-2"><Label>{copy("الاسم بالعربية", "Arabic label")}</Label><Input value={editingComponent.labelAr} required onChange={event => setEditingComponent({ ...editingComponent, labelAr: event.target.value })} /></div><div className="space-y-2"><Label>{copy("الاسم بالإنجليزية", "English label")}</Label><Input value={editingComponent.labelEn} required onChange={event => setEditingComponent({ ...editingComponent, labelEn: event.target.value })} /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setEditingComponent(null)}>{copy("إلغاء", "Cancel")}</Button><Button className="workspace-primary" type="submit">{copy("حفظ التغييرات", "Save changes")}</Button></DialogFooter></form>}</DialogContent></Dialog>
  </BuilderShell>;
}
