import { AppShell } from "@/components/AppShell";
import { WorkspaceAccess } from "@/components/WorkspaceAccess";
import { TemplateVisual } from "@/components/TemplateVisual";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { type TemplateCategory } from "@shared/appBuilderCatalog";
import { componentTypeLabels as catalogLabels, getAllowedComponentTypes, getDefaultComponentProperties, type BuilderComponentType } from "@shared/componentCatalog";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ChevronLeft, ChevronRight, FileAudio, FileImage, FolderPlus, GripVertical, ImagePlus, Layers3, Loader2, MonitorSmartphone, PanelRightOpen, Pencil, Plus, Save, Search, Settings2, Trash2, Upload, X } from "lucide-react";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";

const labels: Record<TemplateCategory, { ar: string; en: string }> = {
  ecommerce: { ar: "متجر إلكتروني", en: "E-commerce" }, education: { ar: "تطبيق تعليمي", en: "Education" }, games: { ar: "تطبيق ألعاب", en: "Games" }, music: { ar: "تطبيق موسيقى", en: "Music" }, podcasts: { ar: "تطبيق بودكاست", en: "Podcasts" }, movies: { ar: "أفلام ومسلسلات", en: "Movies & shows" }, services: { ar: "تطبيق خدمات", en: "Services" },
};

const componentTypeLabels = catalogLabels;
const currencyOptions = ["SAR", "AED", "BHD", "EGP", "EUR", "GBP", "JOD", "KWD", "OMR", "QAR", "USD"] as const;

function BuilderShell({ children }: { children: React.ReactNode }) { return <AppShell><WorkspaceAccess>{children}</WorkspaceAccess></AppShell>; }

function getQueryTemplateId() {
  const value = new URLSearchParams(window.location.search).get("template");
  return value ? Number(value) : undefined;
}

export function CreateProjectPage() {
  const { copy, isArabic } = useLocale();
  const [, setLocation] = useLocation();
  const localUser = trpc.localAuth.me.useQuery();
  const isAuthenticated = Boolean(localUser.data);
  const templates = trpc.appBuilder.templates.list.useQuery();
  const create = trpc.appBuilder.projects.create.useMutation({ onSuccess: ({ id }) => setLocation(`/editor/${id}`) });
  const [templateId, setTemplateId] = useState<number | undefined>(getQueryTemplateId());
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [packageName, setPackageName] = useState("");
  const [language, setLanguage] = useState<"ar" | "en" | "both">("both");
  const selected = templates.data?.find(template => template.id === templateId);

  useEffect(() => { if (!templateId && templates.data?.[0]) setTemplateId(templates.data[0].id); }, [templateId, templates.data]);
  function submit(event: FormEvent) {
    event.preventDefault();
    if (!selected || !isAuthenticated) return;
    create.mutate({ name, description: description || undefined, packageName: packageName || undefined, category: selected.category as TemplateCategory, templateId: selected.id, language });
  }
  return <BuilderShell><div className="builder-heading"><div><Link href="/templates" className="back-link">{isArabic ? <ArrowRight /> : <ArrowLeft />}{copy("العودة للقوالب", "Back to templates")}</Link><p className="section-kicker mt-5">{copy("مشروع جديد", "NEW PROJECT")}</p><h1>{copy("أنشئ تطبيقك من قالب", "Create your app from a template")}</h1><p>{copy("اختر القالب، ثم أعط مشروعك اسمًا وانطلق إلى المحرر.", "Choose a template, name your project, and move directly into the editor.")}</p></div></div>
    <div className="create-layout"><form className="workspace-panel create-form" onSubmit={submit}><div className="form-section-title"><span>01</span><div><h2>{copy("بيانات المشروع", "Project details")}</h2><p>{copy("يمكنك تعديل هذه البيانات لاحقًا من الإعدادات.", "You can update these details later from settings.")}</p></div></div><div className="space-y-2"><Label>{copy("اسم المشروع", "Project name")}</Label><Input value={name} onChange={event => setName(event.target.value)} required minLength={2} placeholder={copy("مثال: متجري الإلكتروني", "Example: My online store")} /></div><div className="space-y-2"><Label>{copy("وصف مختصر", "Short description")}</Label><Textarea value={description} onChange={event => setDescription(event.target.value)} placeholder={copy("ما الفكرة التي سيخدمها تطبيقك؟", "What idea will your app serve?")} /></div><div className="form-split"><div className="space-y-2"><Label>{copy("اسم الحزمة", "Package name")}</Label><Input dir="ltr" value={packageName} onChange={event => setPackageName(event.target.value)} placeholder="com.company.app" /></div><div className="space-y-2"><Label>{copy("لغة التطبيق", "App language")}</Label><div className="segment-control"><button type="button" className={language === "ar" ? "selected" : ""} onClick={() => setLanguage("ar")}>العربية</button><button type="button" className={language === "en" ? "selected" : ""} onClick={() => setLanguage("en")}>English</button><button type="button" className={language === "both" ? "selected" : ""} onClick={() => setLanguage("both")}>{copy("كلاهما", "Both")}</button></div></div></div>
      {create.error && <p className="form-error">{copy("تعذر إنشاء المشروع. سجّل الدخول أولًا ثم أعد المحاولة.", "Could not create the project. Sign in first and try again.")}</p>}{!isAuthenticated && <div className="signin-warning"><p>{copy("يلزم تسجيل الدخول لحفظ مشروعك في حسابك.", "Sign in is required to save a project to your account.")}</p><Link href="/auth"><Button type="button" variant="outline">{copy("تسجيل الدخول", "Sign in")}</Button></Link></div>}<Button type="submit" disabled={!isAuthenticated || create.isPending || !selected || name.trim().length < 2} className="workspace-primary create-submit">{create.isPending ? <Loader2 className="animate-spin" /> : <Plus />}{copy("إنشاء المشروع وفتح المحرر", "Create project & open editor")}</Button></form>
      <aside className="workspace-panel template-picker"><div className="form-section-title"><span>02</span><div><h2>{copy("اختر قالبًا", "Choose a template")}</h2><p>{copy("سيُنشأ هيكل صفحات مقترح تلقائيًا.", "A suggested page structure is created automatically.")}</p></div></div>{templates.isLoading ? <div className="picker-loading"><Loader2 className="animate-spin" /></div> : <div className="picker-list">{templates.data?.map(template => <button type="button" key={template.id} onClick={() => setTemplateId(template.id)} className={cn("picker-item", selected?.id === template.id && "picker-item-active")}><TemplateVisual size="small" iconName={template.iconName} color={template.accentColor} /><div><strong>{isArabic ? template.nameAr : template.nameEn}</strong><span>{labels[template.category as TemplateCategory][isArabic ? "ar" : "en"]}</span></div>{selected?.id === template.id && <span className="picker-check">✓</span>}</button>)}</div>}</aside></div>
  </BuilderShell>;
}

function asRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function propText(properties: Record<string, unknown>, key: string, fallback: string) { const value = properties[key]; return typeof value === "string" && value.trim() ? value : fallback; }
function asItems(properties: Record<string, unknown>) { return Array.isArray(properties.items) ? properties.items.map(asRecord) : []; }

function ComponentsPreview({ components, pages, isArabic, onNavigate }: { components: Array<{ id: number; componentType: string; labelAr: string; labelEn: string; properties: Record<string, unknown> }>; pages: Array<{ id: number; titleAr: string; titleEn: string }>; isArabic: boolean; onNavigate: (pageId: number) => void }) {
  const [searchQuery, setSearchQuery] = useState("");
  if (!components.length) return <div className="preview-empty"><Layers3 /><span>{isArabic ? "أضف مكونات لهذه الصفحة" : "Add components to this page"}</span></div>;
  const pageTitle = (id: unknown) => pages.find(page => page.id === id)?.[isArabic ? "titleAr" : "titleEn"];
  const normalizedQuery = searchQuery.trim().toLocaleLowerCase(isArabic ? "ar" : "en");
  const visibleComponents = components.filter(component => {
    if (component.componentType === "SearchBar" || !normalizedQuery) return true;
    const props = asRecord(component.properties);
    const searchableText = [component.labelAr, component.labelEn, propText(props, "titleAr", ""), propText(props, "titleEn", ""), propText(props, "nameAr", ""), propText(props, "nameEn", ""), propText(props, "descriptionAr", ""), propText(props, "descriptionEn", ""), propText(props, "captionAr", ""), propText(props, "captionEn", "")].join(" ").toLocaleLowerCase(isArabic ? "ar" : "en");
    return searchableText.includes(normalizedQuery);
  });
  const searchComponents = components.filter(component => component.componentType === "SearchBar");
  return <div className="preview-component-stack">{visibleComponents.map((component, index) => {
    const props = asRecord(component.properties);
    const title = (isArabic ? component.labelAr : component.labelEn) || componentTypeLabels[component.componentType as BuilderComponentType]?.[isArabic ? "ar" : "en"] || "";
    if (component.componentType === "SearchBar") return <div key={component.id} className="preview-search"><Search aria-hidden="true" /><input type="search" value={searchQuery} onChange={event => setSearchQuery(event.target.value)} placeholder={propText(props, isArabic ? "placeholderAr" : "placeholderEn", isArabic ? "ابحث في المنتجات" : "Search products")} aria-label={propText(props, isArabic ? "placeholderAr" : "placeholderEn", isArabic ? "ابحث في المنتجات" : "Search products")} />{searchQuery ? <button type="button" onClick={() => setSearchQuery("")} aria-label={isArabic ? "مسح البحث" : "Clear search"}><X /></button> : null}</div>;
    if (component.componentType === "Product") { const currency = propText(props, "currency", "SAR"); const price = typeof props.price === "number" ? props.price : 0; const salePrice = typeof props.salePrice === "number" ? props.salePrice : null; const productName = propText(props, isArabic ? "nameAr" : "nameEn", title); return <article key={component.id} className="preview-product">{typeof props.assetUrl === "string" && props.assetUrl ? <img src={props.assetUrl} alt={productName} /> : <div className="preview-product-placeholder">{isArabic ? "صورة المنتج" : "Product image"}</div>}<div><strong>{productName || (isArabic ? "منتج بدون اسم" : "Untitled product")}</strong><p>{propText(props, isArabic ? "descriptionAr" : "descriptionEn", "")}</p><div className="preview-product-price">{salePrice !== null ? <><del>{price.toLocaleString()} {currency}</del><b>{salePrice.toLocaleString()} {currency}</b></> : <b>{price.toLocaleString()} {currency}</b>}</div><small>{isArabic ? `المتبقي في المخزون: ${typeof props.stock === "number" ? props.stock : 0}` : `Stock remaining: ${typeof props.stock === "number" ? props.stock : 0}`}</small></div></article>; }
    if (component.componentType === "Card") return <article key={component.id} className="preview-card-info" role={typeof props.actionPageId === "number" ? "button" : undefined} tabIndex={typeof props.actionPageId === "number" ? 0 : undefined} onClick={() => typeof props.actionPageId === "number" && onNavigate(props.actionPageId)}><span>{propText(props, isArabic ? "titleAr" : "titleEn", title)}</span><p>{propText(props, isArabic ? "descriptionAr" : "descriptionEn", isArabic ? "أضف وصفًا للبطاقة من الخصائص." : "Add a card description in properties.")}</p>{typeof props.assetUrl === "string" && props.assetUrl ? <img src={props.assetUrl} alt="" /> : null}</article>;
    if (component.componentType === "Button") return <button type="button" key={component.id} className="preview-linked-button" onClick={() => typeof props.targetPageId === "number" && onNavigate(props.targetPageId)}>{propText(props, isArabic ? "textAr" : "textEn", title)}{pageTitle(props.targetPageId) ? <small>{pageTitle(props.targetPageId)}</small> : null}</button>;
    if (component.componentType === "List") { const listTitle = propText(props, isArabic ? "titleAr" : "titleEn", title); return <nav key={component.id} className="preview-nav-list">{listTitle ? <strong className="preview-list-title">{listTitle}</strong> : null}{asItems(props).length ? asItems(props).map((item, itemIndex) => <button type="button" key={`${component.id}-${itemIndex}`} onClick={() => typeof item.targetPageId === "number" && onNavigate(item.targetPageId)}>{propText(item, isArabic ? "labelAr" : "labelEn", isArabic ? "زر تنقل" : "Navigation button")}<i>›</i></button>) : <span>{isArabic ? "أضف أزرار القائمة" : "Add navigation buttons"}<i>›</i></span>}</nav>; }
    if (component.componentType === "Image") return <figure key={component.id} className="preview-media">{typeof props.assetUrl === "string" && props.assetUrl ? <img src={props.assetUrl} alt={propText(props, isArabic ? "altAr" : "altEn", title)} /> : <div>{isArabic ? "اختر صورة من المعرض" : "Choose an image from gallery"}</div>}<figcaption>{propText(props, isArabic ? "altAr" : "altEn", title)}</figcaption></figure>;
    if (component.componentType === "Video") return <figure key={component.id} className="preview-media">{typeof props.assetUrl === "string" && props.assetUrl ? <video controls src={props.assetUrl} /> : <div>{isArabic ? "اختر فيديو من المعرض" : "Choose a video from gallery"}</div>}<figcaption>{propText(props, isArabic ? "captionAr" : "captionEn", title)}</figcaption></figure>;
    if (component.componentType === "Audio") return <figure key={component.id} className="preview-media">{typeof props.assetUrl === "string" && props.assetUrl ? <audio controls preload="metadata" src={props.assetUrl} /> : <div>{isArabic ? "اختر مقطعًا صوتيًا من المعرض" : "Choose an audio clip from gallery"}</div>}<figcaption>{propText(props, isArabic ? "captionAr" : "captionEn", title)}</figcaption></figure>;
    if (component.componentType === "Form") return <form key={component.id} className="preview-form" onSubmit={event => event.preventDefault()}>{(Array.isArray(props.fields) ? props.fields.map(asRecord) : []).slice(0, 3).map((field, fieldIndex) => <input key={`${component.id}-${fieldIndex}`} placeholder={propText(field, isArabic ? "ar" : "en", title)} readOnly />)}<button>{propText(props, isArabic ? "submitLabelAr" : "submitLabelEn", isArabic ? "إرسال" : "Submit")}</button></form>;
    return <div key={component.id} className={cn("preview-component", "preview-game-block", index === 0 && "preview-component-featured")}><span>{componentTypeLabels[component.componentType as BuilderComponentType]?.[isArabic ? "ar" : "en"] ?? component.componentType}</span><strong>{title}</strong><small>{Object.entries(props).filter(([, value]) => ["string", "number", "boolean"].includes(typeof value)).slice(0, 2).map(([key, value]) => `${key}: ${String(value)}`).join(" · ")}</small></div>;
  })}{Boolean(normalizedQuery) && searchComponents.length > 0 && visibleComponents.filter(component => component.componentType !== "SearchBar").length === 0 ? <p className="preview-search-empty">{propText(asRecord(searchComponents[0]?.properties), isArabic ? "emptyAr" : "emptyEn", isArabic ? "لا توجد منتجات مطابقة للبحث" : "No products match your search")}</p> : null}</div>;
}

function ComponentPropertiesFields({ type, properties, onChange, pages, assets, category, isArabic, activePageId }: { type: BuilderComponentType; properties: Record<string, unknown>; onChange: (next: Record<string, unknown>) => void; pages: Array<{ id: number; titleAr: string; titleEn: string }>; assets: Array<{ id: number; url: string; filename: string; mimeType: string }>; category: TemplateCategory; isArabic: boolean; activePageId: number | null }) {
  const copy = (ar: string, en: string) => isArabic ? ar : en;
  const set = (key: string, value: unknown) => onChange({ ...properties, [key]: value });
  const text = (key: string) => typeof properties[key] === "string" ? properties[key] as string : "";
  const numeric = (key: string, fallback: number) => typeof properties[key] === "number" ? properties[key] : fallback;
  const chooseAsset = (assetId: string) => { const asset = assets.find(item => item.id === Number(assetId)); onChange({ ...properties, assetId: asset?.id ?? null, assetUrl: asset?.url ?? "" }); };
  const pageSelect = (key: string) => <select className="editor-select" value={typeof properties[key] === "number" ? String(properties[key]) : ""} onChange={event => set(key, event.target.value ? Number(event.target.value) : null)}><option value="">{copy("بلا رابط", "No link")}</option>{pages.map(page => <option key={page.id} value={page.id}>{isArabic ? page.titleAr : page.titleEn}</option>)}</select>;
  const mediaOptions = (mimePrefix: "image/" | "video/" | "audio/") => <><option value="">{copy("اختر من المعرض", "Choose from gallery")}</option>{assets.filter(asset => asset.mimeType.startsWith(mimePrefix)).map(asset => <option key={asset.id} value={asset.id}>{asset.filename}</option>)}</>;
  if (type === "Card") return <><p className="rounded-lg bg-indigo-50 p-3 text-xs text-indigo-800">{copy("استخدم البطاقة لكتابة درس أو دورة أو مقال. العنوان اختياري والنص هو المحتوى الأساسي.", "Use the card to write a lesson, course, or article. Its title is optional and the text is the main content.")}</p><div className="space-y-2"><Label>{copy("عنوان اختياري بالعربية", "Optional Arabic title")}</Label><Input value={text("titleAr")} onChange={event => set("titleAr", event.target.value)} /></div><div className="space-y-2"><Label>{copy("عنوان اختياري بالإنجليزية", "Optional English title")}</Label><Input value={text("titleEn")} onChange={event => set("titleEn", event.target.value)} /></div><div className="space-y-2"><Label>{copy("نص المحتوى بالعربية", "Arabic content text")}</Label><Textarea value={text("descriptionAr")} onChange={event => set("descriptionAr", event.target.value)} /></div><div className="space-y-2"><Label>{copy("نص المحتوى بالإنجليزية", "English content text")}</Label><Textarea value={text("descriptionEn")} onChange={event => set("descriptionEn", event.target.value)} /></div><div className="space-y-2"><Label>{copy("صفحة إجراء اختيارية", "Optional action page")}</Label>{pageSelect("actionPageId")}</div></>;
  if (type === "Button") return <><div className="space-y-2"><Label>{copy("نص الزر بالعربية", "Arabic button text")}</Label><Input value={text("textAr")} onChange={event => set("textAr", event.target.value)} /></div><div className="space-y-2"><Label>{copy("نص الزر بالإنجليزية", "English button text")}</Label><Input value={text("textEn")} onChange={event => set("textEn", event.target.value)} /></div><div className="space-y-2"><Label>{copy("يربط إلى صفحة", "Links to page")}</Label>{pageSelect("targetPageId")}</div></>;
  if (type === "List") { const items = asItems(properties); const updateItem = (index: number, next: Record<string, unknown>) => onChange({ ...properties, items: items.map((item, itemIndex) => itemIndex === index ? next : item) }); return <div className="space-y-3"><p className="text-xs text-slate-500">{copy("أضف عنوانًا اختياريًا للقائمة، ثم أضف أزرارًا تندرج تحتها. كل زر يحتاج نصًا واحدًا على الأقل وصفحة وجهة.", "Add an optional list title, then nested navigation buttons. Each button needs at least one visible text label and a destination page.")}</p><div className="space-y-2"><Label>{copy("عنوان القائمة بالعربية (اختياري)", "Optional Arabic list title")}</Label><Input value={text("titleAr")} onChange={event => set("titleAr", event.target.value)} /></div><div className="space-y-2"><Label>{copy("عنوان القائمة بالإنجليزية (اختياري)", "Optional English list title")}</Label><Input value={text("titleEn")} onChange={event => set("titleEn", event.target.value)} /></div>{items.map((item, index) => <div key={index} className="rounded-lg border border-slate-200 p-3 space-y-2"><Label>{copy(`زر القائمة ${index + 1}`, `List button ${index + 1}`)}</Label><Input value={propText(item, "labelAr", "")} onChange={event => updateItem(index, { ...item, labelAr: event.target.value })} placeholder={copy("نص الزر بالعربية (مطلوب أحد النصين)", "Arabic button text (one text required)")} /><Input value={propText(item, "labelEn", "")} onChange={event => updateItem(index, { ...item, labelEn: event.target.value })} placeholder={copy("نص الزر بالإنجليزية (مطلوب أحد النصين)", "English button text (one text required)")} /><select className="editor-select" value={typeof item.targetPageId === "number" ? String(item.targetPageId) : ""} onChange={event => updateItem(index, { ...item, targetPageId: event.target.value ? Number(event.target.value) : null })}><option value="">{copy("اختر صفحة الربط (مطلوب)", "Choose link page (required)")}</option>{pages.map(page => <option key={page.id} value={page.id}>{isArabic ? page.titleAr : page.titleEn}</option>)}</select><Button type="button" size="sm" variant="ghost" onClick={() => onChange({ ...properties, items: items.filter((_, itemIndex) => itemIndex !== index) })}>{copy("حذف الزر", "Delete button")}</Button></div>)}<Button type="button" size="sm" variant="outline" onClick={() => onChange({ ...properties, items: [...items, { labelAr: "", labelEn: "", targetPageId: null }] })}><Plus />{copy("إضافة زر للقائمة", "Add list button")}</Button></div>; }
  if (type === "Image" || type === "Video" || type === "Audio") { const isImage = type === "Image"; const mimePrefix = isImage ? "image/" : type === "Video" ? "video/" : "audio/"; const mediaAr = isImage ? "الصورة من المعرض" : type === "Video" ? "الفيديو من المعرض" : "المقطع الصوتي من المعرض"; const mediaEn = isImage ? "Image from gallery" : type === "Video" ? "Video from gallery" : "Audio clip from gallery"; const titleAr = isImage ? "وصف عربي اختياري للصورة" : type === "Video" ? "اسم عربي اختياري للفيديو" : "اسم عربي اختياري للمقطع الصوتي"; const titleEn = isImage ? "Optional Arabic image description" : type === "Video" ? "Optional Arabic video name" : "Optional Arabic audio title"; const englishAr = isImage ? "وصف إنجليزي اختياري للصورة" : type === "Video" ? "اسم إنجليزي اختياري للفيديو" : "اسم إنجليزي اختياري للمقطع الصوتي"; const englishEn = isImage ? "Optional English image description" : type === "Video" ? "Optional English video name" : "Optional English audio title"; return <><div className="space-y-2"><Label>{copy(mediaAr, mediaEn)}</Label><select className="editor-select" value={typeof properties.assetId === "number" ? String(properties.assetId) : ""} onChange={event => chooseAsset(event.target.value)}>{mediaOptions(mimePrefix)}</select></div><div className="space-y-2"><Label>{copy(titleAr, titleEn)}</Label><Input value={text(isImage ? "altAr" : "captionAr")} onChange={event => set(isImage ? "altAr" : "captionAr", event.target.value)} /></div><div className="space-y-2"><Label>{copy(englishAr, englishEn)}</Label><Input value={text(isImage ? "altEn" : "captionEn")} onChange={event => set(isImage ? "altEn" : "captionEn", event.target.value)} /></div></>; }
  if (type === "Product") return <><div className="space-y-2"><Label>{copy("صورة المنتج من المعرض", "Product image from gallery")}</Label><select className="editor-select" value={typeof properties.assetId === "number" ? String(properties.assetId) : ""} onChange={event => chooseAsset(event.target.value)}>{mediaOptions("image/")}</select></div><div className="space-y-2"><Label>{copy("اسم المنتج بالعربية (اختياري)", "Arabic product name (optional)")}</Label><Input value={text("nameAr")} onChange={event => set("nameAr", event.target.value)} /></div><div className="space-y-2"><Label>{copy("اسم المنتج بالإنجليزية (اختياري)", "English product name (optional)")}</Label><Input value={text("nameEn")} onChange={event => set("nameEn", event.target.value)} /></div><div className="space-y-2"><Label>{copy("وصف المنتج بالعربية", "Arabic product description")}</Label><Textarea value={text("descriptionAr")} onChange={event => set("descriptionAr", event.target.value)} /></div><div className="space-y-2"><Label>{copy("وصف المنتج بالإنجليزية", "English product description")}</Label><Textarea value={text("descriptionEn")} onChange={event => set("descriptionEn", event.target.value)} /></div><div className="form-split"><div className="space-y-2"><Label>{copy("السعر", "Price")}</Label><Input type="number" min="0" step="0.01" value={numeric("price", 0)} onChange={event => set("price", Number(event.target.value))} /></div><div className="space-y-2"><Label>{copy("السعر بعد الخصم/التحديث", "Discounted or updated price")}</Label><Input type="number" min="0" step="0.01" value={typeof properties.salePrice === "number" ? properties.salePrice : ""} onChange={event => set("salePrice", event.target.value === "" ? null : Number(event.target.value))} /></div></div><div className="form-split"><div className="space-y-2"><Label>{copy("العملة", "Currency")}</Label><select className="editor-select" value={text("currency") || "SAR"} onChange={event => set("currency", event.target.value)}>{currencyOptions.map(currency => <option key={currency} value={currency}>{currency}</option>)}</select></div><div className="space-y-2"><Label>{copy("المتبقي في المخزون", "Stock remaining")}</Label><Input type="number" min="0" step="1" value={numeric("stock", 0)} onChange={event => set("stock", Number(event.target.value))} /></div></div></>;
  if (type === "SearchBar") return <><p className="rounded-lg bg-blue-50 p-3 text-xs text-blue-800">{copy("يتاح شريط البحث للمتجر والموسيقى والبودكاست والأفلام والمسلسلات، ويُرشّح مكونات الصفحة فور الكتابة في المعاينة.", "The search bar is available in e-commerce, music, podcasts, movies, and shows. It filters page components as you type in preview.")}</p><div className="space-y-2"><Label>{copy("نص البحث بالعربية", "Arabic search placeholder")}</Label><Input value={text("placeholderAr")} onChange={event => set("placeholderAr", event.target.value)} /></div><div className="space-y-2"><Label>{copy("نص البحث بالإنجليزية", "English search placeholder")}</Label><Input value={text("placeholderEn")} onChange={event => set("placeholderEn", event.target.value)} /></div><div className="space-y-2"><Label>{copy("رسالة عدم وجود نتائج بالعربية", "Arabic empty-result message")}</Label><Input value={text("emptyAr")} onChange={event => set("emptyAr", event.target.value)} /></div><div className="space-y-2"><Label>{copy("رسالة عدم وجود نتائج بالإنجليزية", "English empty-result message")}</Label><Input value={text("emptyEn")} onChange={event => set("emptyEn", event.target.value)} /></div></>;
  if (type === "Form") return <><p className="rounded-lg bg-indigo-50 p-3 text-xs text-indigo-800">{copy(`نموذج جاهز لصفحة ${isArabic ? pages.find(page => page.id === (typeof properties.contextPageId === "number" ? properties.contextPageId : activePageId))?.titleAr : pages.find(page => page.id === (typeof properties.contextPageId === "number" ? properties.contextPageId : activePageId))?.titleEn} ضمن قالب ${labels[category]["ar"]}.`, `A ready form for the ${pages.find(page => page.id === (typeof properties.contextPageId === "number" ? properties.contextPageId : activePageId))?.titleEn ?? "current"} page in the ${labels[category]["en"]} template.`)}</p><div className="space-y-2"><Label>{copy("صفحة النموذج", "Form page")}</Label><select className="editor-select" value={typeof properties.contextPageId === "number" ? String(properties.contextPageId) : activePageId ? String(activePageId) : ""} onChange={event => set("contextPageId", event.target.value ? Number(event.target.value) : null)}>{pages.map(page => <option key={page.id} value={page.id}>{isArabic ? page.titleAr : page.titleEn}</option>)}</select></div><div className="space-y-2"><Label>{copy("زر الإرسال بالعربية", "Arabic submit label")}</Label><Input value={text("submitLabelAr")} onChange={event => set("submitLabelAr", event.target.value)} /></div><div className="space-y-2"><Label>{copy("زر الإرسال بالإنجليزية", "English submit label")}</Label><Input value={text("submitLabelEn")} onChange={event => set("submitLabelEn", event.target.value)} /></div></>;
  if (type === "GameScene") return <><div className="space-y-2"><Label>{copy("اسم المشهد", "Scene name")}</Label><Input value={text(isArabic ? "sceneNameAr" : "sceneNameEn")} onChange={event => set(isArabic ? "sceneNameAr" : "sceneNameEn", event.target.value)} /></div><div className="space-y-2"><Label>{copy("المدة بالثواني", "Duration in seconds")}</Label><Input type="number" value={numeric("durationSeconds", 90)} onChange={event => set("durationSeconds", Number(event.target.value))} /></div></>;
  if (type === "Player") return <><div className="space-y-2"><Label>{copy("السرعة", "Speed")}</Label><Input type="number" value={numeric("speed", 6)} onChange={event => set("speed", Number(event.target.value))} /></div><div className="space-y-2"><Label>{copy("قوة القفز", "Jump force")}</Label><Input type="number" value={numeric("jumpForce", 12)} onChange={event => set("jumpForce", Number(event.target.value))} /></div></>;
  if (type === "Physics") return <div className="space-y-2"><Label>{copy("الجاذبية", "Gravity")}</Label><Input type="number" value={numeric("gravity", 1)} onChange={event => set("gravity", Number(event.target.value))} /></div>;
  if (type === "Score") return <><div className="space-y-2"><Label>{copy("النقاط الابتدائية", "Starting score")}</Label><Input type="number" value={numeric("startScore", 0)} onChange={event => set("startScore", Number(event.target.value))} /></div><div className="space-y-2"><Label>{copy("نقاط العنصر", "Points per collectible")}</Label><Input type="number" value={numeric("pointsPerCollectible", 10)} onChange={event => set("pointsPerCollectible", Number(event.target.value))} /></div></>;
  if (type === "Level") return <><div className="space-y-2"><Label>{copy("رقم المستوى", "Level number")}</Label><Input type="number" value={numeric("levelNumber", 1)} onChange={event => set("levelNumber", Number(event.target.value))} /></div><div className="space-y-2"><Label>{copy("هدف النقاط", "Target score")}</Label><Input type="number" value={numeric("targetScore", 100)} onChange={event => set("targetScore", Number(event.target.value))} /></div></>;
  return <><div className="space-y-2"><Label>{copy("القيمة المستهدفة", "Target value")}</Label><Input type="number" value={numeric("targetValue", 100)} onChange={event => set("targetValue", Number(event.target.value))} /></div><div className="space-y-2"><Label>{copy("صفحة النجاح", "Success page")}</Label>{pageSelect("successPageId")}</div><div className="space-y-2"><Label>{copy("صفحة الفشل", "Failure page")}</Label>{pageSelect("failurePageId")}</div></>;
}

export function EditorPage() {
  const { copy, isArabic } = useLocale();
  const [, params] = useRoute("/editor/:id");
  const projectId = Number(params?.id);
  const workspace = trpc.appBuilder.projects.getWorkspace.useQuery(projectId, { enabled: Number.isFinite(projectId), retry: false });
  const utils = trpc.useUtils();
  const [activePageId, setActivePageId] = useState<number | null>(null);
  const [newPage, setNewPage] = useState(false);
  const [pageAr, setPageAr] = useState("");
  const [pageEn, setPageEn] = useState("");
  const [componentAr, setComponentAr] = useState("");
  const [componentEn, setComponentEn] = useState("");
  const [componentType, setComponentType] = useState<BuilderComponentType>("Card");
  const [assetMessage, setAssetMessage] = useState("");
  const [editingPage, setEditingPage] = useState<{ id: number; titleAr: string; titleEn: string; route: string } | null>(null);
  const [editingComponent, setEditingComponent] = useState<{ id: number; componentType: BuilderComponentType; labelAr: string; labelEn: string; properties: Record<string, unknown> } | null>(null);
  const invalidate = () => utils.appBuilder.projects.getWorkspace.invalidate(projectId);
  const addPage = trpc.appBuilder.editor.addPage.useMutation({ onSuccess: () => { setNewPage(false); setPageAr(""); setPageEn(""); invalidate(); } });
  const deletePage = trpc.appBuilder.editor.deletePage.useMutation({ onSuccess: invalidate });
  const updatePage = trpc.appBuilder.editor.updatePage.useMutation({ onSuccess: invalidate });
  const addComponent = trpc.appBuilder.editor.addComponent.useMutation({ onSuccess: (created, input) => { const category = workspace.data?.project.category as TemplateCategory | undefined; const defaults = category ? getDefaultComponentProperties(input.componentType, category) : {}; setComponentAr(""); setComponentEn(""); setEditingComponent({ id: created.id, componentType: input.componentType, labelAr: input.labelAr ?? "", labelEn: input.labelEn ?? "", properties: { ...defaults, ...input.properties } }); invalidate(); }, onError: () => setAssetMessage(copy("تعذر إضافة المكون. تحقق من إعداداته ثم أعد المحاولة.", "Could not add the component. Check its settings and try again.")) });
  const updateComponent = trpc.appBuilder.editor.updateComponent.useMutation({ onSuccess: invalidate });
  const reorderComponents = trpc.appBuilder.editor.reorderComponents.useMutation({ onSuccess: invalidate });
  const deleteComponent = trpc.appBuilder.editor.deleteComponent.useMutation({ onSuccess: invalidate });
  const uploadAsset = trpc.appBuilder.assets.upload.useMutation({ onSuccess: () => { setAssetMessage(copy("تم رفع الملف. افتح إعداد الصورة أو الفيديو أو الصوت واختره من المعرض.", "File uploaded. Open the image, video, or audio settings and choose it from the gallery.")); utils.appBuilder.assets.list.invalidate(projectId); }, onError: () => setAssetMessage(copy("تعذر رفع الملف. تأكد من نوعه وحجمه ثم أعد المحاولة.", "Could not upload the file. Check its type and size, then try again.")) });
  const assets = trpc.appBuilder.assets.list.useQuery(projectId, { enabled: Number.isFinite(projectId), retry: false });
  const reorderPages = trpc.appBuilder.editor.reorderPages.useMutation({ onSuccess: invalidate });
  const pages = workspace.data?.pages ?? [];
  const activePage = pages.find(page => page.id === activePageId) ?? pages[0];
  const pageComponents = workspace.data?.components.filter(component => component.pageId === activePage?.id) ?? [];
  useEffect(() => { if (!activePageId && pages[0]) setActivePageId(pages[0].id); }, [activePageId, pages]);
  function handleAsset(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !projectId) return; const expandedMedia = file.type.startsWith("video/") || file.type.startsWith("audio/"); const sizeLimit = expandedMedia ? 25 * 1024 * 1024 : 5 * 1024 * 1024; if (file.size > sizeLimit) { setAssetMessage(copy(expandedMedia ? "الحد الأقصى للفيديو والصوت هو 25 ميغابايت." : "الحد الأقصى للملف هو 5 ميغابايت.", expandedMedia ? "Video and audio are limited to 25 MB." : "This file is limited to 5 MB.")); event.target.value = ""; return; } const reader = new FileReader(); reader.onload = () => { const data = String(reader.result).split(",")[1]; if (data) uploadAsset.mutate({ projectId, filename: file.name, mimeType: file.type || "application/octet-stream", kind: file.type.startsWith("image/") ? "image" : "other", dataBase64: data }); }; reader.readAsDataURL(file); }
  function movePage(pageId: number, direction: -1 | 1) { const index = pages.findIndex(page => page.id === pageId); const target = index + direction; if (index < 0 || target < 0 || target >= pages.length) return; const reordered = [...pages]; [reordered[index], reordered[target]] = [reordered[target], reordered[index]]; reorderPages.mutate({ projectId, pageIds: reordered.map(page => page.id) }); }
  function moveComponent(componentId: number, direction: -1 | 1) { if (!activePage) return; const index = pageComponents.findIndex(component => component.id === componentId); const target = index + direction; if (index < 0 || target < 0 || target >= pageComponents.length) return; const reordered = [...pageComponents]; [reordered[index], reordered[target]] = [reordered[target], reordered[index]]; reorderComponents.mutate({ projectId, pageId: activePage.id, componentIds: reordered.map(component => component.id) }); }
  function editPage(page: typeof pages[number]) { setEditingPage({ id: page.id, titleAr: page.titleAr, titleEn: page.titleEn, route: page.route }); }
  function editComponent(component: typeof pageComponents[number]) { setEditingComponent({ id: component.id, componentType: component.componentType as BuilderComponentType, labelAr: component.labelAr, labelEn: component.labelEn, properties: asRecord(component.properties) }); }
  if (workspace.isLoading) return <BuilderShell><div className="editor-loading"><Loader2 className="animate-spin" />{copy("يتم تحميل المحرر…", "Loading editor…")}</div></BuilderShell>;
  if (!workspace.data) return <BuilderShell><div className="editor-error"><FolderPlus /><h1>{copy("المشروع غير متاح", "Project unavailable")}</h1><p>{copy("سجّل الدخول ثم أنشئ مشروعًا جديدًا لفتح المحرر.", "Sign in and create a project to open the editor.")}</p><Link href="/create"><Button className="workspace-primary">{copy("إنشاء مشروع", "Create project")}</Button></Link></div></BuilderShell>;
  const allowedComponentTypes = getAllowedComponentTypes(workspace.data.project.category as TemplateCategory);
  return <BuilderShell><div className="editor-topline"><div><Link href="/projects" className="back-link">{isArabic ? <ArrowRight /> : <ArrowLeft />}{copy("مشاريعي", "My projects")}</Link><div className="editor-project-title"><span className="section-kicker">{labels[workspace.data.project.category as TemplateCategory]?.[isArabic ? "ar" : "en"]}</span><h1>{workspace.data.project.name}</h1></div></div><div className="editor-actions"><label className="asset-upload"><FileAudio />{copy("رفع صورة أو فيديو أو صوت", "Upload image, video, or audio")}<input type="file" accept="image/*,video/*,audio/*,.ttf,.otf,.pdf" onChange={handleAsset} /></label><Link href={`/run/${projectId}`}><Button variant="outline"><MonitorSmartphone />{copy("تشغيل التطبيق", "Run app")}</Button></Link><span className="inline-flex items-center gap-2 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700"><Save className="h-4 w-4" />{copy("الحفظ تلقائي", "Auto-saved")}</span></div></div>{assetMessage && <div className="asset-message">{assetMessage}<button onClick={() => setAssetMessage("")}><X /></button></div>}
    <div className="editor-layout"><aside className="editor-pages workspace-panel"><div className="editor-panel-heading"><div><h2>{copy("صفحات التطبيق", "App pages")}</h2><span>{pages.length}</span></div><button onClick={() => setNewPage(true)}><Plus /></button></div><div className="page-nav-list">{pages.map((page, index) => <div className={cn("page-nav-item", activePage?.id === page.id && "page-nav-item-active")} key={page.id}><button onClick={() => setActivePageId(page.id)}><GripVertical /><span>{isArabic ? page.titleAr : page.titleEn}</span></button><div className="page-nav-actions"><button className="page-move" onClick={() => editPage(page)} aria-label={copy("تعديل الصفحة", "Edit page")}><Pencil /></button><button className="page-move" disabled={index === 0 || reorderPages.isPending} onClick={() => movePage(page.id, -1)} aria-label={copy("نقل الصفحة للأعلى", "Move page up")}><ArrowUp /></button><button className="page-move" disabled={index === pages.length - 1 || reorderPages.isPending} onClick={() => movePage(page.id, 1)} aria-label={copy("نقل الصفحة للأسفل", "Move page down")}><ArrowDown /></button><button className="delete-mini" onClick={() => deletePage.mutate({ projectId, pageId: page.id })} aria-label={copy("حذف الصفحة", "Delete page")}><Trash2 /></button></div></div>)}</div>{newPage && <form className="inline-form" onSubmit={event => { event.preventDefault(); addPage.mutate({ projectId, titleAr: pageAr, titleEn: pageEn, route: `/${pageEn.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-") || "page"}` }); }}><Input value={pageAr} onChange={event => setPageAr(event.target.value)} placeholder={copy("عنوان عربي", "Arabic title")} required /><Input value={pageEn} onChange={event => setPageEn(event.target.value)} placeholder={copy("عنوان إنجليزي", "English title")} required /><div><Button size="sm" type="submit">{copy("إضافة", "Add")}</Button><Button size="sm" type="button" variant="ghost" onClick={() => setNewPage(false)}>{copy("إلغاء", "Cancel")}</Button></div></form>}</aside>
      <section className="editor-canvas workspace-panel"><div className="canvas-toolbar"><div><span>{copy("معاينة مباشرة", "Live preview")}</span><strong>{isArabic ? activePage?.titleAr : activePage?.titleEn}</strong></div><div className="device-tabs"><button className="active">{copy("جوال", "Mobile")}</button><button>{copy("لوحي", "Tablet")}</button></div></div><div className="phone-frame"><div className="phone-notch" /><div className="phone-appbar"><span className="phone-logo" /><strong>{isArabic ? activePage?.titleAr : activePage?.titleEn}</strong><span>•••</span></div><div className="phone-content"><h3>{isArabic ? activePage?.titleAr : activePage?.titleEn}</h3><p>{copy("هذه معاينة بنية الصفحة والمكونات التي تضيفها.", "This previews the page structure and components you add.")}</p><ComponentsPreview components={pageComponents} pages={pages} isArabic={isArabic} onNavigate={setActivePageId} /></div><div className="phone-bottom"><i /><i className="active" /><i /></div></div></section>
      <aside className="editor-properties workspace-panel"><div className="editor-panel-heading"><div><h2>{copy("المكونات", "Components")}</h2><span>{pageComponents.length}</span></div><PanelRightOpen /></div><form className="component-form" onSubmit={event => { event.preventDefault(); if (!activePage) return; addComponent.mutate({ projectId, pageId: activePage.id, componentType, labelAr: componentAr, labelEn: componentEn, properties: componentType === "Form" ? { contextPageId: activePage.id } : {} }); }}><Label>{copy("نوع المكون", "Component type")}</Label><select value={componentType} onChange={event => setComponentType(event.target.value as BuilderComponentType)}>{allowedComponentTypes.map(type => <option key={type} value={type}>{componentTypeLabels[type][isArabic ? "ar" : "en"]}</option>)}</select><Input value={componentAr} onChange={event => setComponentAr(event.target.value)} placeholder={copy("اسم المكون بالعربية (اختياري)", "Arabic label (optional)")} /><Input value={componentEn} onChange={event => setComponentEn(event.target.value)} placeholder={copy("اسم المكون بالإنجليزية (اختياري)", "English label (optional)")} /><Button type="submit" variant="outline"><Plus />{copy("إضافة مكون", "Add component")}</Button></form><div className="component-list">{pageComponents.map((component, index) => <div key={component.id} className="component-list-item"><div><span>{componentTypeLabels[component.componentType as BuilderComponentType]?.[isArabic ? "ar" : "en"] ?? component.componentType}</span><strong>{(isArabic ? component.labelAr : component.labelEn) || componentTypeLabels[component.componentType as BuilderComponentType]?.[isArabic ? "ar" : "en"]}</strong></div><div className="component-row-actions"><button disabled={index === 0 || reorderComponents.isPending} onClick={() => moveComponent(component.id, -1)} aria-label={copy("نقل المكون للأعلى", "Move component up")}><ArrowUp /></button><button disabled={index === pageComponents.length - 1 || reorderComponents.isPending} onClick={() => moveComponent(component.id, 1)} aria-label={copy("نقل المكون للأسفل", "Move component down")}><ArrowDown /></button><button onClick={() => editComponent(component)} aria-label={copy("تعديل المكون", "Edit component")}><Pencil /></button><button onClick={() => deleteComponent.mutate({ projectId, componentId: component.id })} aria-label={copy("حذف المكون", "Delete component")}><Trash2 /></button></div></div>)}</div><div className="editor-assets"><div className="editor-assets-heading"><FileImage /><span>{copy("الأصول المرفوعة", "Uploaded assets")}</span></div>{assets.isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : assets.data?.length ? <div className="asset-list">{assets.data.map(asset => <a href={asset.url} target="_blank" rel="noreferrer" key={asset.id} className="asset-list-item"><ImagePlus /><span>{asset.filename}</span></a>)}</div> : <p>{copy("لم ترفع أي أصول بعد.", "No assets uploaded yet.")}</p>}</div></aside></div>
    <Dialog open={Boolean(editingPage)} onOpenChange={open => { if (!open) setEditingPage(null); }}><DialogContent dir={isArabic ? "rtl" : "ltr"}><DialogHeader><DialogTitle>{copy("تعديل الصفحة", "Edit page")}</DialogTitle><DialogDescription>{copy("حدّث أسماء الصفحة ومسارها داخل التطبيق.", "Update the page names and its route in the app.")}</DialogDescription></DialogHeader>{editingPage && <form className="space-y-4" onSubmit={event => { event.preventDefault(); updatePage.mutate({ projectId, pageId: editingPage.id, titleAr: editingPage.titleAr, titleEn: editingPage.titleEn, route: editingPage.route }); setEditingPage(null); }}><div className="space-y-2"><Label>{copy("العنوان بالعربية", "Arabic title")}</Label><Input value={editingPage.titleAr} required onChange={event => setEditingPage({ ...editingPage, titleAr: event.target.value })} /></div><div className="space-y-2"><Label>{copy("العنوان بالإنجليزية", "English title")}</Label><Input value={editingPage.titleEn} required onChange={event => setEditingPage({ ...editingPage, titleEn: event.target.value })} /></div><div className="space-y-2"><Label>{copy("المسار", "Route")}</Label><Input dir="ltr" value={editingPage.route} required onChange={event => setEditingPage({ ...editingPage, route: event.target.value })} /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setEditingPage(null)}>{copy("إلغاء", "Cancel")}</Button><Button className="workspace-primary" type="submit">{copy("حفظ التغييرات", "Save changes")}</Button></DialogFooter></form>}</DialogContent></Dialog>
    <Dialog open={Boolean(editingComponent)} onOpenChange={open => { if (!open) setEditingComponent(null); }}><DialogContent className="max-h-[85vh] overflow-y-auto" dir={isArabic ? "rtl" : "ltr"}><DialogHeader><DialogTitle>{copy("إعداد المكون", "Configure component")}</DialogTitle><DialogDescription>{copy("عدّل محتوى المكون ووظيفته وروابطه أو أصله من المعرض.", "Configure its content, behavior, links, or gallery asset.")}</DialogDescription></DialogHeader>{editingComponent && <form className="space-y-4" onSubmit={event => { event.preventDefault(); updateComponent.mutate({ projectId, componentId: editingComponent.id, componentType: editingComponent.componentType, labelAr: editingComponent.labelAr, labelEn: editingComponent.labelEn, properties: editingComponent.properties }); setEditingComponent(null); }}><div className="space-y-2"><Label>{copy("نوع المكون", "Component type")}</Label><select className="editor-select" value={editingComponent.componentType} onChange={event => setEditingComponent({ ...editingComponent, componentType: event.target.value as BuilderComponentType })}>{allowedComponentTypes.map(type => <option key={type} value={type}>{componentTypeLabels[type][isArabic ? "ar" : "en"]}</option>)}</select></div><div className="space-y-2"><Label>{copy("الاسم بالعربية (اختياري)", "Arabic label (optional)")}</Label><Input value={editingComponent.labelAr} onChange={event => setEditingComponent({ ...editingComponent, labelAr: event.target.value })} /></div><div className="space-y-2"><Label>{copy("الاسم بالإنجليزية (اختياري)", "English label (optional)")}</Label><Input value={editingComponent.labelEn} onChange={event => setEditingComponent({ ...editingComponent, labelEn: event.target.value })} /></div><ComponentPropertiesFields type={editingComponent.componentType} properties={editingComponent.properties} onChange={properties => setEditingComponent({ ...editingComponent, properties })} pages={pages} assets={assets.data ?? []} category={workspace.data.project.category as TemplateCategory} isArabic={isArabic} activePageId={activePage?.id ?? null} /><DialogFooter><Button type="button" variant="outline" onClick={() => setEditingComponent(null)}>{copy("إلغاء", "Cancel")}</Button><Button className="workspace-primary" type="submit">{copy("حفظ التغييرات", "Save changes")}</Button></DialogFooter></form>}</DialogContent></Dialog>
  </BuilderShell>;
}
