import { AppShell } from "@/components/AppShell";
import { WorkspaceAccess } from "@/components/WorkspaceAccess";
import { Button } from "@/components/ui/button";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { ArrowLeft, ArrowRight, ChevronLeft, ChevronRight, CircleAlert, FileAudio, Image as ImageIcon, Layers3, Loader2, Search, ShoppingBag, Video, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";

function asRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function text(properties: Record<string, unknown>, key: string, fallback = "") { const value = properties[key]; return typeof value === "string" && value.trim() ? value : fallback; }
function items(properties: Record<string, unknown>) { return Array.isArray(properties.items) ? properties.items.map(asRecord) : []; }

type RuntimeComponent = { id: number; componentType: string; labelAr: string; labelEn: string; properties: unknown };
type RuntimePage = { id: number; titleAr: string; titleEn: string; route: string };

function ProjectScreen({ components, pages, activePageId, onNavigate, isArabic }: { components: RuntimeComponent[]; pages: RuntimePage[]; activePageId: number; onNavigate: (pageId: number) => void; isArabic: boolean }) {
  const [query, setQuery] = useState("");
  const [submitted, setSubmitted] = useState<number | null>(null);
  const currentComponents = components.filter(component => component.componentType === "SearchBar" || !query.trim() || `${component.labelAr} ${component.labelEn} ${text(asRecord(component.properties), "titleAr")} ${text(asRecord(component.properties), "titleEn")} ${text(asRecord(component.properties), "nameAr")} ${text(asRecord(component.properties), "nameEn")} ${text(asRecord(component.properties), "descriptionAr")} ${text(asRecord(component.properties), "descriptionEn")}`.toLocaleLowerCase(isArabic ? "ar" : "en").includes(query.trim().toLocaleLowerCase(isArabic ? "ar" : "en")));
  const pageTitle = (id: unknown) => pages.find(page => page.id === id)?.[isArabic ? "titleAr" : "titleEn"];
  const searchConfiguration = components.find(component => component.componentType === "SearchBar");
  const searchProps = asRecord(searchConfiguration?.properties);

  if (!components.length) return <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500"><Layers3 className="mx-auto mb-3 h-8 w-8 text-indigo-400" /><strong className="block text-slate-800">{isArabic ? "هذه الصفحة فارغة" : "This page is empty"}</strong><p className="mt-1 text-sm">{isArabic ? "ارجع إلى المحرر وأضف صورًا أو فيديو أو صوتًا أو أزرارًا أو قائمة." : "Return to the editor and add images, video, audio, buttons, or a list."}</p></div>;

  return <div className="space-y-4">{currentComponents.map(component => {
    const props = asRecord(component.properties);
    const label = (isArabic ? component.labelAr : component.labelEn) || component.componentType;
    if (component.componentType === "SearchBar") return <div key={component.id} className="flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><Search className="h-5 w-5 text-slate-400" /><input className="min-w-0 flex-1 bg-transparent text-sm outline-none" type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder={text(props, isArabic ? "placeholderAr" : "placeholderEn", isArabic ? "ابحث" : "Search")} />{query && <button type="button" onClick={() => setQuery("")} aria-label={isArabic ? "مسح البحث" : "Clear search"}><X className="h-4 w-4 text-slate-400" /></button>}</div>;
    if (component.componentType === "Image") return <figure key={component.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{text(props, "assetUrl") ? <img className="max-h-[28rem] w-full object-cover" src={text(props, "assetUrl")} alt={text(props, isArabic ? "altAr" : "altEn", label)} /> : <div className="flex aspect-[16/8] items-center justify-center bg-slate-100 text-slate-400"><ImageIcon /></div>}<figcaption className="px-4 py-3 text-sm text-slate-600">{text(props, isArabic ? "altAr" : "altEn", label)}</figcaption></figure>;
    if (component.componentType === "Video") return <figure key={component.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{text(props, "assetUrl") ? <video className="w-full bg-black" controls preload="metadata" src={text(props, "assetUrl")} /> : <div className="flex aspect-video items-center justify-center bg-slate-900 text-slate-300"><Video /></div>}<figcaption className="px-4 py-3 text-sm text-slate-600">{text(props, isArabic ? "captionAr" : "captionEn", label)}</figcaption></figure>;
    if (component.componentType === "Audio") return <figure key={component.id} className="rounded-3xl border border-indigo-100 bg-indigo-50 p-5"><div className="mb-3 flex items-center gap-3"><span className="rounded-2xl bg-indigo-600 p-3 text-white"><FileAudio className="h-5 w-5" /></span><strong className="text-slate-900">{text(props, isArabic ? "captionAr" : "captionEn", label)}</strong></div>{text(props, "assetUrl") ? <audio className="w-full" controls preload="metadata" src={text(props, "assetUrl")} /> : <p className="text-sm text-slate-500">{isArabic ? "لم يُحدد ملف صوتي بعد." : "No audio attachment selected yet."}</p>}</figure>;
    if (component.componentType === "Button") { const target = typeof props.targetPageId === "number" ? props.targetPageId : null; return <button key={component.id} type="button" onClick={() => target && onNavigate(target)} disabled={!target} className={cn("flex w-full items-center justify-between rounded-2xl px-5 py-4 text-start font-bold shadow-sm transition active:scale-[0.98]", target ? "bg-gradient-to-l from-indigo-600 to-violet-600 text-white" : "cursor-not-allowed bg-slate-200 text-slate-500")}>{text(props, isArabic ? "textAr" : "textEn", label)}{target ? <span className="flex items-center gap-2 text-xs font-medium text-white/80">{pageTitle(target)}{isArabic ? <ArrowLeft className="h-4 w-4" /> : <ArrowRight className="h-4 w-4" />}</span> : <span className="text-xs">{isArabic ? "اختر صفحة الربط" : "Choose link page"}</span>}</button>; }
    if (component.componentType === "List") { const listItems = items(props); const title = text(props, isArabic ? "titleAr" : "titleEn", label); return <nav key={component.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{title && <div className="border-b border-slate-100 px-5 py-4"><strong className="text-slate-900">{title}</strong></div>}{listItems.length ? listItems.map((item, index) => { const target = typeof item.targetPageId === "number" ? item.targetPageId : null; return <button type="button" key={`${component.id}-${index}`} onClick={() => target && onNavigate(target)} disabled={!target} className="flex w-full items-center justify-between border-b border-slate-100 px-5 py-4 text-start text-sm font-semibold text-slate-700 last:border-0 disabled:cursor-not-allowed disabled:text-slate-400">{text(item, isArabic ? "labelAr" : "labelEn", isArabic ? "زر قائمة" : "List button")}{isArabic ? <ChevronLeft className="h-4 w-4 text-indigo-500" /> : <ChevronRight className="h-4 w-4 text-indigo-500" />}</button>; }) : <p className="px-5 py-4 text-sm text-slate-500">{isArabic ? "لا توجد أزرار داخل هذه القائمة بعد." : "This list has no buttons yet."}</p>}</nav>; }
    if (component.componentType === "Product") { const price = typeof props.price === "number" ? props.price : 0; const salePrice = typeof props.salePrice === "number" ? props.salePrice : null; const currency = text(props, "currency", "SAR"); return <article key={component.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{text(props, "assetUrl") ? <img src={text(props, "assetUrl")} className="h-48 w-full object-cover" alt="" /> : <div className="flex h-40 items-center justify-center bg-slate-100 text-slate-400"><ShoppingBag /></div>}<div className="p-5"><strong className="text-lg text-slate-900">{text(props, isArabic ? "nameAr" : "nameEn", label)}</strong><p className="mt-1 text-sm leading-6 text-slate-600">{text(props, isArabic ? "descriptionAr" : "descriptionEn")}</p><div className="mt-4 flex items-end justify-between"><div>{salePrice !== null ? <><del className="mr-2 text-sm text-slate-400">{price} {currency}</del><strong className="text-indigo-700">{salePrice} {currency}</strong></> : <strong className="text-indigo-700">{price} {currency}</strong>}</div><span className="text-xs text-slate-500">{isArabic ? `المخزون: ${typeof props.stock === "number" ? props.stock : 0}` : `Stock: ${typeof props.stock === "number" ? props.stock : 0}`}</span></div></div></article>; }
    if (component.componentType === "Card") { const target = typeof props.actionPageId === "number" ? props.actionPageId : null; return <article key={component.id} onClick={() => target && onNavigate(target)} className={cn("rounded-3xl border border-slate-200 bg-white p-5 shadow-sm", target && "cursor-pointer transition hover:border-indigo-300")}>{text(props, isArabic ? "titleAr" : "titleEn", label) && <strong className="block text-lg text-slate-900">{text(props, isArabic ? "titleAr" : "titleEn", label)}</strong>}<p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-600">{text(props, isArabic ? "descriptionAr" : "descriptionEn", isArabic ? "أضف المحتوى من المحرر." : "Add content from the editor.")}</p>{target && <span className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-indigo-600">{isArabic ? "فتح الصفحة" : "Open page"}{isArabic ? <ArrowLeft className="h-3.5 w-3.5" /> : <ArrowRight className="h-3.5 w-3.5" />}</span>}</article>; }
    if (component.componentType === "Form") { const fields = Array.isArray(props.fields) ? props.fields.map(asRecord) : []; return <form key={component.id} onSubmit={event => { event.preventDefault(); setSubmitted(component.id); }} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4"><strong className="text-slate-900">{label}</strong><p className="mt-1 text-sm text-slate-500">{isArabic ? "نموذج مخصص لهذه الصفحة" : "A form tailored to this page"}</p></div><div className="space-y-3">{fields.map((field, index) => <input key={`${component.id}-${index}`} required={field.required === true} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-indigo-500" placeholder={text(field, isArabic ? "ar" : "en", isArabic ? "حقل" : "Field")} type={text(field, "type", "text")} />)}</div><Button type="submit" className="mt-4 w-full">{text(props, isArabic ? "submitLabelAr" : "submitLabelEn", isArabic ? "إرسال" : "Submit")}</Button>{submitted === component.id && <p className="mt-3 text-sm font-medium text-emerald-700">{isArabic ? "تم تسجيل النموذج في المعاينة." : "The form was recorded in this preview."}</p>}</form>; }
    return <div key={component.id} className="rounded-2xl border border-slate-200 bg-white p-4 text-sm text-slate-600"><strong className="block text-slate-900">{label}</strong><span className="mt-1 block">{isArabic ? "يظهر هذا المكون في التطبيق بعد إعداد خصائصه." : "This component appears in the app after its properties are configured."}</span></div>;
  })}{query.trim() && currentComponents.filter(component => component.componentType !== "SearchBar").length === 0 && <div className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-800">{text(searchProps, isArabic ? "emptyAr" : "emptyEn", isArabic ? "لا توجد نتائج مطابقة." : "No matching results.")}</div>}</div>;
}

export default function ProjectRuntimePage() {
  const { copy, isArabic } = useLocale();
  const [, params] = useRoute("/run/:id");
  const projectId = Number(params?.id);
  const workspace = trpc.appBuilder.projects.getWorkspace.useQuery(projectId, { enabled: Number.isFinite(projectId), retry: false });
  const [activePageId, setActivePageId] = useState<number | null>(null);
  const pages = workspace.data?.pages ?? [];
  useEffect(() => { if (!activePageId && pages[0]) setActivePageId(pages[0].id); }, [activePageId, pages]);
  const activePage = useMemo(() => pages.find(page => page.id === activePageId) ?? pages[0], [pages, activePageId]);
  const components = workspace.data?.components.filter(component => component.pageId === activePage?.id) ?? [];
  const Arrow = isArabic ? ArrowRight : ArrowLeft;

  return <AppShell><WorkspaceAccess>{workspace.isLoading ? <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-indigo-600" /></div> : !workspace.data || !activePage ? <div className="mx-auto max-w-xl py-20 text-center"><CircleAlert className="mx-auto mb-4 h-10 w-10 text-amber-500" /><h1 className="text-2xl font-bold text-slate-900">{copy("تعذر فتح التطبيق", "Unable to open app")}</h1><p className="mt-2 text-slate-600">{copy("تأكد من وجود المشروع في حسابك ثم أعد المحاولة.", "Confirm the project belongs to your account, then try again.")}</p></div> : <main className="mx-auto max-w-5xl px-4 py-7 md:px-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link href={`/editor/${projectId}`} className="inline-flex items-center gap-2 text-sm font-semibold text-indigo-700"><Arrow className="h-4 w-4" />{copy("العودة إلى المحرر", "Back to editor")}</Link><p className="mt-3 text-xs font-bold tracking-[0.16em] text-indigo-500">{copy("وضع تشغيل التطبيق", "APP RUN MODE")}</p><h1 className="mt-1 text-2xl font-black text-slate-950">{workspace.data.project.name}</h1></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">{copy("تفاعل حقيقي", "Live interactions")}</span></div><div className="grid gap-6 lg:grid-cols-[13rem_minmax(0,1fr)]"><aside className="rounded-3xl border border-slate-200 bg-white p-3 shadow-sm"><p className="px-3 py-2 text-xs font-bold uppercase tracking-widest text-slate-400">{copy("شاشات التطبيق", "App screens")}</p><nav className="space-y-1">{pages.map(page => <button type="button" key={page.id} onClick={() => setActivePageId(page.id)} className={cn("w-full rounded-2xl px-3 py-3 text-start text-sm font-semibold transition", page.id === activePage.id ? "bg-indigo-600 text-white shadow" : "text-slate-600 hover:bg-slate-50")}>{isArabic ? page.titleAr : page.titleEn}</button>)}</nav></aside><section className="min-w-0 rounded-[2rem] border border-slate-200 bg-slate-50 p-3 shadow-sm md:p-5"><div className="mx-auto max-w-md overflow-hidden rounded-[2.4rem] border-[8px] border-slate-900 bg-white shadow-2xl"><div className="flex items-center justify-between bg-slate-900 px-5 py-3 text-xs text-white/80"><span>{workspace.data.project.name}</span><span>•••</span></div><div className="min-h-[36rem] bg-slate-50 p-4"><h2 className="mb-4 text-xl font-black text-slate-950">{isArabic ? activePage.titleAr : activePage.titleEn}</h2><ProjectScreen components={components as RuntimeComponent[]} pages={pages} activePageId={activePage.id} onNavigate={setActivePageId} isArabic={isArabic} /></div></div></section></div></main>}</WorkspaceAccess></AppShell>;
}
