import { BrandMark } from "@/components/BrandMark";
import { LanguageToggle } from "@/components/LanguageToggle";
import { TemplateVisual } from "@/components/TemplateVisual";
import { Button } from "@/components/ui/button";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { premiumExampleCatalog } from "@shared/premiumExamples";
import { componentTypeLabels } from "@shared/componentCatalog";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleHelp, Crown, FileBox, Layers3, LockKeyhole, MonitorSmartphone, Sparkles } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import "./public-pages.css";

const labels = { ecommerce: { ar: "متجر إلكتروني", en: "E-commerce" }, education: { ar: "تطبيق تعليمي", en: "Education" }, games: { ar: "تطبيق ألعاب", en: "Games" }, music: { ar: "تطبيق موسيقى", en: "Music" }, podcasts: { ar: "تطبيق بودكاست", en: "Podcasts" }, movies: { ar: "أفلام ومسلسلات", en: "Movies & shows" }, services: { ar: "تطبيق خدمات", en: "Services" } } as const;

function PublicHeader() { const { copy } = useLocale(); return <header className="public-header container"><Link href="/"><BrandMark /></Link><div><Link href="/guide" className="public-header-link"><CircleHelp />{copy("الدليل", "Guide")}</Link><LanguageToggle /><Link href="/auth"><Button variant="outline">{copy("تسجيل الدخول", "Sign in")}</Button></Link></div></header>; }

function ExampleUseAction({ slug, isArabic }: { slug: string; isArabic: boolean }) {
  const { data: user, isLoading } = trpc.localAuth.me.useQuery();
  const [, setLocation] = useLocation();
  const createProject = trpc.appBuilder.projects.createFromExample.useMutation({ onSuccess: created => setLocation(`/editor/${created.id}`) });
  const copy = (ar: string, en: string) => isArabic ? ar : en;
  if (isLoading) return <Button className="workspace-primary" disabled>{copy("جارٍ التحقق من الحساب", "Checking account")}</Button>;
  if (!user) return <Link href="/auth"><Button className="workspace-primary">{copy("سجّل الدخول لاستخدام المثال", "Sign in to use this example")}{isArabic ? <ArrowLeft /> : <ArrowRight />}</Button></Link>;
  return <div className="example-use-action"><Button className="workspace-primary" onClick={() => createProject.mutate({ slug })} disabled={createProject.isPending}>{createProject.isPending ? copy("جارٍ إنشاء مشروعك", "Creating your project") : copy("استخدم المثال في مشروعك", "Use this example")}{isArabic ? <ArrowLeft /> : <ArrowRight />}</Button>{createProject.isError && <p role="alert">{copy("تعذر إنشاء المشروع. حاول مرة أخرى.", "Unable to create the project. Please try again.")}</p>}</div>;
}

export function GuidePage() {
  const { copy, isArabic } = useLocale();
  const Arrow = isArabic ? ArrowLeft : ArrowRight;
  const steps = [{ icon: Layers3, title: copy("ابدأ بالقوالب", "Start with templates"), text: copy("اختر قالبًا أساسيًا مجانًا، أو افتح معاينات التطبيقات المكتملة لتتعرف على بنيتها.", "Choose a base template for free, or open complete app previews to explore their structure.") }, { icon: FileBox, title: copy("اختر مسار التصدير", "Choose an export path"), text: copy("المسار المجاني مستقل بالكامل. أما التصدير المدفوع فيحسب حسب الفئة وكل 10 ميغابايت ويمنح أمثلة حصرية.", "The free path is fully independent. Paid export is priced by category and each 10 MB, with exclusive examples.") }, { icon: MonitorSmartphone, title: copy("تابع حالة البناء", "Track build status"), text: copy("تظهر حالة APK وAAB وIPA في مركز التصدير. إنتاج الملفات النهائية يتطلب ربط خدمة البناء السحابية.", "APK, AAB, and IPA status appears in Export Center. Final artifacts require the cloud-build service connection.") }];
  return <div className="public-page"><PublicHeader /><main className="container public-main"><section className="guide-hero"><div><p className="section-kicker"><CircleHelp />{copy("دليل App Builder", "APP BUILDER GUIDE")}</p><h1>{copy("دليلك من الفكرة إلى طلب التصدير", "Your guide from idea to export request")}</h1><p>{copy("استخدم هذا الدليل لفهم الفرق بين النسخة المجانية والتصدير المدفوع وأمثلة التطبيقات وخطوات البناء.", "Use this guide to understand free access, paid export, application examples, and the build steps.")}</p><Link href="/templates"><Button className="workspace-primary">{copy("استعرض القوالب", "Browse templates")}<Arrow /></Button></Link></div><div className="guide-hero-mark"><Sparkles /><strong>{copy("عربي وإنجليزي", "Arabic & English")}</strong><span>{copy("دعم RTL وLTR", "RTL & LTR ready")}</span></div></section><section className="guide-steps">{steps.map(step => <article key={step.title}><span><step.icon /></span><h2>{step.title}</h2><p>{step.text}</p></article>)}</section><section className="guide-note"><LockKeyhole /><div><h2>{copy("أين أجد أمثلة التطبيقات؟", "Where are the app examples?")}</h2><p>{copy("يمكنك فتح معاينة كل مثال من الصفحة الرئيسية أو مكتبة القوالب، ثم تسجيل الدخول لإنشاء نسخة قابلة للتحرير منه. يظل التصدير المدفوع مرتبطًا بمسار التحصيل فقط.", "Open each example preview from the home page or template library, then sign in to create an editable copy. Paid export remains tied only to the collection flow.")}</p></div></section></main></div>;
}

export function PremiumExamplePreviewPage() {
  const { copy, isArabic } = useLocale();
  const [, params] = useRoute("/examples/:slug");
  const example = premiumExampleCatalog.find(item => item.slug === params?.slug);
  const Arrow = isArabic ? ArrowLeft : ArrowRight;
  if (!example) return <div className="public-page"><PublicHeader /><main className="container public-main"><div className="public-empty"><h1>{copy("المثال غير متاح", "Example unavailable")}</h1><Link href="/"><Button>{copy("العودة للرئيسية", "Back home")}</Button></Link></div></main></div>;
  return <div className="public-page"><PublicHeader /><main className="container public-main"><Link href="/" className="public-back"><Arrow />{copy("العودة للأمثلة", "Back to examples")}</Link><section className="example-preview-hero"><div><div className="example-preview-badge"><Crown />{copy("مثال قالب متكامل", "COMPLETE TEMPLATE EXAMPLE")}</div><h1>{isArabic ? example.nameAr : example.nameEn}</h1><p>{isArabic ? example.descriptionAr : example.descriptionEn}</p><p className="example-preview-category">{labels[example.category][isArabic ? "ar" : "en"]}</p><ExampleUseAction slug={example.slug} isArabic={isArabic} /></div><div className="example-preview-visual"><TemplateVisual iconName={example.iconName} color={example.accentColor} /><span>{example.pages.length} {copy("شاشات", "screens")}</span></div></section><section className="example-layout"><div className="example-pages-card"><div className="example-section-heading"><Layers3 /><div><h2>{copy("شاشات التطبيق", "App screens")}</h2><p>{copy("بنية تتحول إلى مشروع قابل للتحرير بعد تسجيل الدخول.", "A structure that becomes an editable project after sign-in.")}</p></div></div>{example.pages.map((page, index) => <div className="example-page-row" key={page.key}><strong>{String(index + 1).padStart(2, "0")}</strong><div><h3>{isArabic ? page.titleAr : page.titleEn}</h3><span>/{page.key}</span></div><CheckCircle2 /></div>)}</div><aside className="example-components-card"><div className="example-section-heading"><Sparkles /><div><h2>{copy("المكونات الأساسية", "Core components")}</h2><p>{copy("تكوينات حقيقية قابلة للتحرير تُنشأ داخل المشروع عند استخدام المثال.", "Real editable component configurations created inside your project when you use this example.")}</p></div></div><div className="example-component-tags">{example.components.map((component, index) => <span key={`${component.pageKey}-${component.componentType}-${index}`}>{componentTypeLabels[component.componentType][isArabic ? "ar" : "en"]} · {isArabic ? example.pages.find(page => page.key === component.pageKey)?.titleAr : example.pages.find(page => page.key === component.pageKey)?.titleEn}</span>)}</div><div className="example-lock-note"><LockKeyhole /><p>{copy("المعاينة متاحة للجميع. بعد تسجيل الدخول يمكنك إنشاء نسخة تملكها وتعديلها، بينما يظل التصدير المدفوع منفصلًا عن هذا الإجراء.", "Preview is open to everyone. After signing in, you can create and edit an owned copy; paid export remains separate from this action.")}</p></div></aside></section></main></div>;
}
