import { BrandMark } from "@/components/BrandMark";
import { LanguageToggle } from "@/components/LanguageToggle";
import { TemplateVisual } from "@/components/TemplateVisual";
import { Button } from "@/components/ui/button";
import { useLocale } from "@/contexts/LocaleContext";
import { premiumExampleCatalog } from "@shared/premiumExamples";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleHelp, Crown, FileBox, Layers3, LockKeyhole, MonitorSmartphone, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";
import "./public-pages.css";

const labels = { ecommerce: { ar: "متجر إلكتروني", en: "E-commerce" }, education: { ar: "تطبيق تعليمي", en: "Education" }, games: { ar: "تطبيق ألعاب", en: "Games" }, music: { ar: "تطبيق موسيقى", en: "Music" }, podcasts: { ar: "تطبيق بودكاست", en: "Podcasts" }, movies: { ar: "أفلام ومسلسلات", en: "Movies & shows" }, services: { ar: "تطبيق خدمات", en: "Services" } } as const;

function PublicHeader() { const { copy } = useLocale(); return <header className="public-header container"><Link href="/"><BrandMark /></Link><div><Link href="/guide" className="public-header-link"><CircleHelp />{copy("الدليل", "Guide")}</Link><LanguageToggle /><Link href="/auth"><Button variant="outline">{copy("تسجيل الدخول", "Sign in")}</Button></Link></div></header>; }

export function GuidePage() {
  const { copy, isArabic } = useLocale();
  const Arrow = isArabic ? ArrowLeft : ArrowRight;
  const steps = [{ icon: Layers3, title: copy("ابدأ بالقوالب", "Start with templates"), text: copy("اختر قالبًا أساسيًا مجانًا، أو افتح معاينات التطبيقات المكتملة لتتعرف على بنيتها.", "Choose a base template for free, or open complete app previews to explore their structure.") }, { icon: FileBox, title: copy("اختر مسار التصدير", "Choose an export path"), text: copy("المسار المجاني مستقل بالكامل. أما التصدير المدفوع فيحسب حسب الفئة وكل 10 ميغابايت ويمنح أمثلة حصرية.", "The free path is fully independent. Paid export is priced by category and each 10 MB, with exclusive examples.") }, { icon: MonitorSmartphone, title: copy("تابع حالة البناء", "Track build status"), text: copy("تظهر حالة APK وAAB وIPA في مركز التصدير. إنتاج الملفات النهائية يتطلب ربط خدمة البناء السحابية.", "APK, AAB, and IPA status appears in Export Center. Final artifacts require the cloud-build service connection.") }];
  return <div className="public-page"><PublicHeader /><main className="container public-main"><section className="guide-hero"><div><p className="section-kicker"><CircleHelp />{copy("دليل App Builder", "APP BUILDER GUIDE")}</p><h1>{copy("دليلك من الفكرة إلى طلب التصدير", "Your guide from idea to export request")}</h1><p>{copy("استخدم هذا الدليل لفهم الفرق بين النسخة المجانية والتصدير المدفوع وأمثلة التطبيقات وخطوات البناء.", "Use this guide to understand free access, paid export, application examples, and the build steps.")}</p><Link href="/templates"><Button className="workspace-primary">{copy("استعرض القوالب", "Browse templates")}<Arrow /></Button></Link></div><div className="guide-hero-mark"><Sparkles /><strong>{copy("عربي وإنجليزي", "Arabic & English")}</strong><span>{copy("دعم RTL وLTR", "RTL & LTR ready")}</span></div></section><section className="guide-steps">{steps.map(step => <article key={step.title}><span><step.icon /></span><h2>{step.title}</h2><p>{step.text}</p></article>)}</section><section className="guide-note"><LockKeyhole /><div><h2>{copy("أين أجد أمثلة التطبيقات؟", "Where are the app examples?")}</h2><p>{copy("يمكنك فتح معاينة كل مثال من الصفحة الرئيسية أو مكتبة القوالب. تبقى معاينة البنية متاحة، بينما إنشاء مثال قابل للتحرير والتصدير المدفوع يتطلب تفعيل مسار التحصيل.", "Open each example preview from the home page or template library. Structure previews are available, while creating an editable example and paid export require enabling the collection flow.")}</p></div></section></main></div>;
}

export function PremiumExamplePreviewPage() {
  const { copy, isArabic } = useLocale();
  const [, params] = useRoute("/examples/:slug");
  const example = premiumExampleCatalog.find(item => item.slug === params?.slug);
  const Arrow = isArabic ? ArrowLeft : ArrowRight;
  if (!example) return <div className="public-page"><PublicHeader /><main className="container public-main"><div className="public-empty"><h1>{copy("المثال غير متاح", "Example unavailable")}</h1><Link href="/"><Button>{copy("العودة للرئيسية", "Back home")}</Button></Link></div></main></div>;
  return <div className="public-page"><PublicHeader /><main className="container public-main"><Link href="/" className="public-back"><Arrow />{copy("العودة للأمثلة", "Back to examples")}</Link><section className="example-preview-hero"><div><div className="example-preview-badge"><Crown />{copy("مثال حصري للنسخة المدفوعة", "PAID EXAMPLE")}</div><h1>{isArabic ? example.nameAr : example.nameEn}</h1><p>{isArabic ? example.descriptionAr : example.descriptionEn}</p><p className="example-preview-category">{labels[example.category][isArabic ? "ar" : "en"]}</p><Link href="/auth"><Button className="workspace-primary">{copy("سجّل الدخول لاستخدام المثال", "Sign in to use this example")}<Arrow /></Button></Link></div><div className="example-preview-visual"><TemplateVisual iconName={example.iconName} color={example.accentColor} /><span>{example.pages.length} {copy("شاشات", "screens")}</span></div></section><section className="example-layout"><div className="example-pages-card"><div className="example-section-heading"><Layers3 /><div><h2>{copy("شاشات التطبيق", "App screens")}</h2><p>{copy("بنية قابلة للتحرير عند تفعيل المثال المدفوع.", "An editable structure when the paid example is enabled.")}</p></div></div>{example.pages.map((page, index) => <div className="example-page-row" key={page.key}><strong>{String(index + 1).padStart(2, "0")}</strong><div><h3>{isArabic ? page.titleAr : page.titleEn}</h3><span>/{page.key}</span></div><CheckCircle2 /></div>)}</div><aside className="example-components-card"><div className="example-section-heading"><Sparkles /><div><h2>{copy("المكونات الأساسية", "Core components")}</h2><p>{copy("عناصر مبدئية لتسريع التخصيص.", "Starter elements for faster customization.")}</p></div></div><div className="example-component-tags">{example.components.map(component => <span key={component}>{component}</span>)}</div><div className="example-lock-note"><LockKeyhole /><p>{copy("المعاينة متاحة الآن. إنشاء نسخة قابلة للتحرير والتصدير المدفوع يظهران بعد تفعيل التحصيل.", "Preview is available now. Creating an editable copy and paid export appear after collection is enabled.")}</p></div></aside></section></main></div>;
}
