import { AppShell } from "@/components/AppShell";
import { WorkspaceAccess } from "@/components/WorkspaceAccess";
import { TemplateVisual } from "@/components/TemplateVisual";
import { PremiumExamplesPanel } from "@/components/PremiumExamplesPanel";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { templateCategories, type TemplateCategory } from "@shared/appBuilderCatalog";
import { componentTypeLabels } from "@shared/componentCatalog";
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, FileBox, FolderPlus, ImagePlus, Layers3, Loader2, Pencil, Play, Plus, Search, Sparkles, Trash2, UploadCloud } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";

type WorkspaceProps = { children: React.ReactNode };
function Workspace({ children }: WorkspaceProps) { return <AppShell><WorkspaceAccess>{children}</WorkspaceAccess></AppShell>; }

function PageHeading({ kicker, title, description, action }: { kicker?: string; title: string; description: string; action?: React.ReactNode }) {
  return <div className="page-heading"><div><p className="section-kicker">{kicker}</p><h1>{title}</h1><p>{description}</p></div>{action}</div>;
}

function LoadingPanel() { return <div className="workspace-panel loading-panel"><Loader2 className="h-5 w-5 animate-spin text-indigo-500" /></div>; }

const unknownCategoryLabel = { ar: "تطبيق مخصص", en: "Custom app" };
const categoryLabels: Record<string, { ar: string; en: string }> = new Proxy({
  ecommerce: { ar: "متجر إلكتروني", en: "E-commerce" }, education: { ar: "تطبيق تعليمي", en: "Education" }, games: { ar: "تطبيق ألعاب", en: "Games" }, music: { ar: "تطبيق موسيقى", en: "Music" }, podcasts: { ar: "تطبيق بودكاست", en: "Podcasts" }, movies: { ar: "أفلام ومسلسلات", en: "Movies & shows" }, services: { ar: "تطبيق خدمات", en: "Services" }, books: { ar: "تطبيق كتب", en: "Books App" },
}, { get: (labels, category: string | symbol) => typeof category === "string" ? labels[category as keyof typeof labels] ?? unknownCategoryLabel : undefined });

const unknownExportStatusLabel = { ar: "قيد المعالجة", en: "Processing" };
const exportStatusLabels: Record<string, { ar: string; en: string }> = new Proxy({
  draft: { ar: "مسودة", en: "Draft" }, pending_payment: { ar: "طلب قديم متوقف", en: "Archived request" }, queued: { ar: "في قائمة البناء", en: "Build queued" }, building: { ar: "قيد البناء", en: "Building" }, ready: { ar: "جاهز للتنزيل", en: "Ready to download" }, failed: { ar: "تعذر البناء", en: "Build failed" }, cancelled: { ar: "ملغى", en: "Cancelled" },
}, { get: (labels, status: string | symbol) => typeof status === "string" ? labels[status as keyof typeof labels] ?? unknownExportStatusLabel : undefined });
const unknownComponentLabel = { ar: "مكوّن", en: "Component" };
function localizedComponentLabel(componentType: string, isArabic: boolean) { return (componentTypeLabels as Record<string, { ar: string; en: string }>)[componentType]?.[isArabic ? "ar" : "en"] ?? unknownComponentLabel[isArabic ? "ar" : "en"]; }

export function DashboardPage() {
  const { copy, isArabic } = useLocale();
  const templatesQuery = trpc.appBuilder.templates.list.useQuery();
  const projectsQuery = trpc.appBuilder.projects.list.useQuery(undefined, { retry: false });
  const Arrow = isArabic ? ArrowLeft : ArrowRight;
  const templates = templatesQuery.data?.slice(0, 3) ?? [];
  const projectCount = projectsQuery.data?.length ?? 0;
  return <Workspace><PageHeading kicker={copy("لوحة العمل", "WORKSPACE")} title={copy("صباح الإبداع", "Good morning, creator")} description={copy("ابدأ مشروعًا جديدًا أو تابع تعديل أحد مشاريعك.", "Start a new project or continue shaping one of your apps.")} action={<Link href="/templates"><Button className="workspace-primary"><Plus className="h-4 w-4" />{copy("إنشاء مشروع جديد", "Create new project")}</Button></Link>} />
    <section className="dashboard-stats"><article><span className="stat-icon stat-icon-indigo"><Layers3 /></span><div><strong>{projectCount}</strong><p>{copy("مشروعاتك", "Your projects")}</p></div></article><article><span className="stat-icon stat-icon-blue"><FileBox /></span><div><strong>7</strong><p>{copy("قوالب جاهزة", "Ready templates")}</p></div></article><article><span className="stat-icon stat-icon-green"><UploadCloud /></span><div><strong>3</strong><p>{copy("صيغ تصدير", "Export formats")}</p></div></article></section>
    <section className="dashboard-grid"><div className="workspace-panel recent-panel"><div className="panel-heading"><div><h2>{copy("المشاريع الأخيرة", "Recent projects")}</h2><p>{copy("مساحة مخصصة لمشاريع حسابك.", "A dedicated space for your account projects.")}</p></div><Link href="/projects" className="text-link">{copy("عرض الكل", "View all")}<Arrow className="h-4 w-4" /></Link></div>{projectsQuery.isLoading ? <LoadingPanel /> : projectCount ? <div className="project-list">{projectsQuery.data?.slice(0, 3).map(project => <Link href={`/editor/${project.id}`} className="project-row" key={project.id}><div className="project-row-icon"><FolderPlus /></div><div><strong>{project.name}</strong><p>{categoryLabels[project.category as TemplateCategory][isArabic ? "ar" : "en"]}</p></div><ChevronRight className="row-chevron" /></Link>)}</div> : <div className="empty-project"><div><FolderPlus /></div><strong>{copy("لم تُنشئ مشروعًا بعد", "No projects yet")}</strong><p>{copy("اختر قالبًا احترافيًا وابدأ من هيكل جاهز.", "Choose a professional template and start with a ready structure.")}</p><Link href="/templates"><Button variant="outline">{copy("استعراض القوالب", "Browse templates")}</Button></Link></div>}</div>
      <div className="workspace-panel readiness-panel"><div className="readiness-mark"><Sparkles /></div><p className="section-kicker">{copy("خطوة البداية", "FIRST STEP")}</p><h2>{copy("اختر قالبًا وابدأ التخصيص", "Pick a template and start tailoring")}</h2><p>{copy("لكل قالب مكونات وهيكل صفحات مقترح لتبدأ أسرع.", "Each template includes components and a suggested page structure.")}</p><Link href="/templates"><Button className="workspace-primary w-full">{copy("الانتقال إلى القوالب", "Go to templates")}<Arrow className="h-4 w-4" /></Button></Link></div></section>
    <section className="template-strip"><div className="panel-heading"><div><h2>{copy("قوالب مقترحة", "Suggested templates")}</h2><p>{copy("انطلق من بنية مدروسة بدل البدء من صفحة فارغة.", "Start from a considered structure instead of a blank page.")}</p></div><Link href="/templates" className="text-link">{copy("كل القوالب", "All templates")}</Link></div>{templatesQuery.isLoading ? <LoadingPanel /> : <div className="suggestion-grid">{templates.map(template => <Link href={`/templates?selected=${template.id}`} className="suggestion-card" key={template.id}><TemplateVisual iconName={template.iconName} color={template.accentColor} /><div><strong>{isArabic ? template.nameAr : template.nameEn}</strong><p>{(isArabic ? template.descriptionAr : template.descriptionEn).slice(0, 72)}…</p></div><ChevronLeft className="suggestion-arrow" /></Link>)}</div>}</section>
  </Workspace>;
}

export function TemplatesPage() {
  const { copy, isArabic } = useLocale();
  const { data: templates, isLoading } = trpc.appBuilder.templates.list.useQuery();
  const [query, setQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState<TemplateCategory | "all">("all");
  const shown = (templates ?? []).filter(template => (activeCategory === "all" || template.category === activeCategory) && `${template.nameAr} ${template.nameEn}`.toLowerCase().includes(query.toLowerCase()));
  return <Workspace><PageHeading kicker={copy("مكتبة القوالب", "TEMPLATE LIBRARY")} title={copy("قوالب جاهزة لفكرتك", "Ready templates for your idea")} description={copy("اختر الفئة المناسبة، ثم عدّل الصفحات والمكونات وفق احتياج تطبيقك.", "Select a category, then tailor pages and components to your app.")} />
    <div className="template-toolbar"><div className="search-field"><Search /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder={copy("ابحث في القوالب", "Search templates")} /></div><div className="category-pills"><button className={activeCategory === "all" ? "active" : ""} onClick={() => setActiveCategory("all")}>{copy("الكل", "All")}</button>{templateCategories.map(category => <button key={category} className={activeCategory === category ? "active" : ""} onClick={() => setActiveCategory(category)}>{categoryLabels[category][isArabic ? "ar" : "en"]}</button>)}</div></div>
    {isLoading ? <LoadingPanel /> : <><div className="template-library-grid">{shown.map(template => <article className="template-library-card" key={template.id}><div className="template-card-top"><TemplateVisual iconName={template.iconName} color={template.accentColor} /><span className="template-category" style={{ color: template.accentColor, background: `${template.accentColor}14` }}>{categoryLabels[template.category as TemplateCategory][isArabic ? "ar" : "en"]}</span></div><h2>{isArabic ? template.nameAr : template.nameEn}</h2><p>{isArabic ? template.descriptionAr : template.descriptionEn}</p><div className="component-tags">{template.components.slice(0, 3).map(component => <span key={component}>{localizedComponentLabel(component, isArabic)}</span>)}</div><div className="template-card-footer"><span>{template.suggestedStructure.length} {copy("صفحات مقترحة", "suggested pages")}</span><Link href={`/create?template=${template.id}`}><Button variant="outline" size="sm">{copy("اختيار القالب", "Choose template")}</Button></Link></div></article>)}</div><PremiumExamplesPanel isArabic={isArabic} /></>}
  </Workspace>;
}

export function ProjectsPage() {
  const { copy, isArabic } = useLocale();
  const projects = trpc.appBuilder.projects.list.useQuery(undefined, { retry: false });
  const utils = trpc.useUtils();
  const [deleteError, setDeleteError] = useState("");
  const [editingProject, setEditingProject] = useState<{ id: number; name: string; description: string } | null>(null);
  const removeProject = trpc.appBuilder.projects.remove.useMutation({ onSuccess: () => utils.appBuilder.projects.list.invalidate(), onError: () => setDeleteError(copy("تعذر حذف المشروع. حاول مرة أخرى.", "Could not delete the project. Try again.")) });
  const updateProject = trpc.appBuilder.projects.update.useMutation({ onSuccess: () => { utils.appBuilder.projects.list.invalidate(); setEditingProject(null); }, onError: () => setDeleteError(copy("تعذر حفظ تغييرات المشروع. حاول مرة أخرى.", "Could not save project changes. Try again.")) });
  function requestRemoval(projectId: number, projectName: string) {
    if (window.confirm(copy(`هل تريد حذف مشروع «${projectName}»؟ لا يمكن التراجع عن هذا الإجراء.`, `Delete “${projectName}”? This action cannot be undone.`))) removeProject.mutate(projectId);
  }
  return <Workspace><PageHeading kicker={copy("إدارة المشاريع", "PROJECT MANAGEMENT")} title={copy("مشاريعي", "My projects")} description={copy("تتبع مسوداتك وتابع تعديل بنية التطبيقات من مكان واحد.", "Track drafts and continue editing your app structures from one place.")} action={<Link href="/templates"><Button className="workspace-primary"><Plus className="h-4 w-4" />{copy("مشروع جديد", "New project")}</Button></Link>} />
    {deleteError && <p className="form-error" role="alert">{deleteError}</p>}<section className="workspace-panel projects-table-panel">{projects.isLoading ? <LoadingPanel /> : projects.data?.length ? <div className="projects-table"><div className="projects-head"><span>{copy("المشروع", "Project")}</span><span>{copy("الفئة", "Category")}</span><span>{copy("الحالة", "Status")}</span><span>{copy("آخر تعديل", "Last updated")}</span><span>{copy("إجراء", "Action")}</span></div>{projects.data.map(project => <div className="projects-row" key={project.id}><Link href={`/editor/${project.id}`} className="project-row-link"><strong>{project.name}</strong><span>{categoryLabels[project.category as TemplateCategory][isArabic ? "ar" : "en"]}</span><span className="status-pill"><Clock3 />{project.status === "draft" ? copy("مسودة", "Draft") : copy("قيد التحديث", "Updating")}</span><span>{new Date(project.updatedAt).toLocaleDateString(isArabic ? "ar-SA" : "en-US")}</span></Link><div className="project-row-actions"><Link href={`/run/${project.id}`}><Button type="button" size="icon" variant="ghost" className="project-edit" aria-label={copy("تشغيل التطبيق", "Run app")}><Play /></Button></Link><Button type="button" size="icon" variant="ghost" className="project-edit" onClick={() => setEditingProject({ id: project.id, name: project.name, description: project.description ?? "" })} aria-label={copy("تعديل المشروع", "Edit project")}><Pencil /></Button><Button type="button" size="icon" variant="ghost" className="project-delete" disabled={removeProject.isPending} onClick={() => requestRemoval(project.id, project.name)} aria-label={copy("حذف المشروع", "Delete project")}><Trash2 /></Button></div></div>)}</div> : <div className="big-empty"><div className="empty-icon"><FolderPlus /></div><h2>{copy("ابدأ بمشروعك الأول", "Start your first project")}</h2><p>{copy("اختر أحد القوالب السبعة لتنشئ هيكل تطبيقك وتعدله باحترافية.", "Pick one of seven templates to create and professionally tailor your app structure.")}</p><Link href="/templates"><Button className="workspace-primary">{copy("اختيار قالب", "Choose a template")}</Button></Link></div>}</section>
    <Dialog open={Boolean(editingProject)} onOpenChange={open => { if (!open) setEditingProject(null); }}><DialogContent dir={isArabic ? "rtl" : "ltr"}><DialogHeader><DialogTitle>{copy("تعديل تفاصيل المشروع", "Edit project details")}</DialogTitle><DialogDescription>{copy("حدّث اسم المشروع ووصفه؛ يُنشأ المعرّف التقني تلقائيًا من اسم المشروع.", "Update the app name and description; its technical identifier is generated from the name automatically.")}</DialogDescription></DialogHeader>{editingProject && <form className="space-y-4" onSubmit={event => { event.preventDefault(); updateProject.mutate({ projectId: editingProject.id, data: { name: editingProject.name, description: editingProject.description || undefined } }); }}><div className="space-y-2"><Label>{copy("اسم المشروع", "Project name")}</Label><Input value={editingProject.name} minLength={2} required onChange={event => setEditingProject({ ...editingProject, name: event.target.value })} /></div><div className="space-y-2"><Label>{copy("الوصف", "Description")}</Label><Input value={editingProject.description} onChange={event => setEditingProject({ ...editingProject, description: event.target.value })} /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setEditingProject(null)}>{copy("إلغاء", "Cancel")}</Button><Button type="submit" className="workspace-primary" disabled={updateProject.isPending}>{updateProject.isPending && <Loader2 className="animate-spin" />}{copy("حفظ التغييرات", "Save changes")}</Button></DialogFooter></form>}</DialogContent></Dialog>
  </Workspace>;
}

export function ExportsPage() {
  const { copy, isArabic } = useLocale();
  const jobs = trpc.appBuilder.exports.list.useQuery(undefined, { retry: false });
  const projects = trpc.appBuilder.projects.list.useQuery(undefined, { retry: false });
  const [projectId, setProjectId] = useState<number | null>(null);
  const [preferredFormat, setPreferredFormat] = useState<"apk" | "aab" | "ipa">("apk");
  const [exportNotice, setExportNotice] = useState("");
  const utils = trpc.useUtils();
  const selectedProject = projects.data?.find(project => project.id === projectId);
  const hasPaidCategory = selectedProject?.category !== "books" && selectedProject?.category !== "custom";
  const paidQuote = trpc.appBuilder.exports.quotePaid.useQuery({ projectId: projectId ?? 1, format: preferredFormat }, { enabled: Boolean(projectId && hasPaidCategory), retry: false });
  useEffect(() => { if (!projectId && projects.data?.[0]) setProjectId(projects.data[0].id); }, [projectId, projects.data]);
  useEffect(() => {
    const selected = projects.data?.find(project => project.id === projectId);
    const selectedFormat = selected?.settings?.exportFormat;
    if (selectedFormat === "apk" || selectedFormat === "aab" || selectedFormat === "ipa") setPreferredFormat(selectedFormat);
  }, [projectId, projects.data]);
  const createExport = trpc.appBuilder.exports.create.useMutation({ onSuccess: () => { utils.appBuilder.exports.list.invalidate(); setExportNotice(copy("تمت إضافة طلب التصدير المجاني إلى قائمة البناء.", "Your free export request is now in the build queue.")); }, onError: () => setExportNotice(copy("تعذر إضافة طلب التصدير. حاول مرة أخرى.", "We could not queue the export request. Please try again.")) });
  const refreshExports = trpc.appBuilder.exports.refresh.useMutation({ onSuccess: () => { utils.appBuilder.exports.list.invalidate(); setExportNotice(copy("تم تحديث حالة ملفات التصدير.", "Export file status was refreshed.")); }, onError: () => setExportNotice(copy("تعذر تحديث حالة البناء الآن.", "Build status could not be refreshed right now.")) });
  const requestExport = (format: "apk" | "aab" | "ipa") => { if (!projectId) { setExportNotice(copy("أنشئ مشروعًا أولًا ثم اطلب ملف التصدير.", "Create a project first, then request an export.")); return; } createExport.mutate({ projectId, format }); };
  return <Workspace><PageHeading kicker={copy("مركز التصدير", "EXPORT CENTER")} title={copy("جهّز ملف تطبيقك", "Prepare your app file")} description={copy("اختر مشروعك وأضف ملفك مجانًا إلى قائمة البناء.", "Choose your project and add its file to the build queue for free.")} />
    <div className="exports-layout"><section className="workspace-panel export-builder"><div className="panel-heading"><div><h2>{copy("طلب تصدير جديد", "New export request")}</h2><p>{copy("اختر الصيغة لإضافة طلبك مجانًا إلى قائمة البناء.", "Choose a format to add your request to the build queue for free.")}</p></div><span className="template-category">{copy("مجاني بالكامل", "Fully free")}</span></div><div className="form-grid export-form-grid"><div className="space-y-2"><Label>{copy("المشروع", "Project")}</Label><Select value={projectId ? String(projectId) : ""} onValueChange={value => setProjectId(Number(value))}><SelectTrigger><SelectValue placeholder={copy("اختر مشروعًا", "Choose a project")} /></SelectTrigger><SelectContent>{projects.data?.map(project => <SelectItem value={String(project.id)} key={project.id}>{project.name}</SelectItem>)}</SelectContent></Select></div></div><p className="mt-4 rounded-xl bg-indigo-50 px-4 py-3 text-sm font-semibold text-indigo-800">{copy(`الصيغة المختارة عند إنشاء المشروع: ${preferredFormat.toUpperCase()}`, `Format selected when creating this project: ${preferredFormat.toUpperCase()}`)}</p>{exportNotice && <div className="payment-notice" role="status">{exportNotice}</div>}<div className="format-buttons"><Button disabled={createExport.isPending} onClick={() => requestExport("apk")} className="format-button" variant={preferredFormat === "apk" ? "default" : "outline"}><FileBox />APK {preferredFormat === "apk" && <small>{copy("المحدد", "Selected")}</small>}</Button><Button disabled={createExport.isPending} onClick={() => requestExport("aab")} className="format-button" variant={preferredFormat === "aab" ? "default" : "outline"}><FileBox />AAB {preferredFormat === "aab" && <small>{copy("المحدد", "Selected")}</small>}</Button><Button disabled={createExport.isPending} onClick={() => requestExport("ipa")} className="format-button" variant={preferredFormat === "ipa" ? "default" : "outline"}><FileBox />IPA {preferredFormat === "ipa" && <small>{copy("المحدد", "Selected")}</small>}</Button></div><p className="export-note"><Sparkles />{copy("يتطلب إنشاء الملفات الفعلية ربط خدمة البناء السحابية. ويتطلب IPA أيضًا حساب Apple Developer وشهادات التوقيع الخاصة بك.", "Actual files still require the cloud-build connection; IPA also requires your Apple Developer account and signing certificates.")}</p></section>
      <section className="workspace-panel export-builder"><div className="panel-heading"><div><h2>{copy("تقدير التصدير المدفوع", "Paid export quote")}</h2><p>{copy("المسار المدفوع مستقل عن التصدير المجاني ويحسب بالريال لكل 10 ميغابايت.", "The paid path is independent from free export and is calculated in SAR for each 10 MB.")}</p></div><span className="template-category">{copy("تقدير فقط", "Quote only")}</span></div>{!projectId ? <p className="compact-empty">{copy("اختر مشروعًا لعرض التقدير المدفوع.", "Select a project to view its paid quote.")}</p> : selectedProject?.category === "books" ? <p className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800">{copy("لم يُعتمد سعر التصدير المدفوع لقالب الكتب بعد، لذا لا نعرض أو ننشئ فاتورة له.", "A paid export price for Books has not been approved yet, so no quote or invoice is available.")}</p> : paidQuote.isLoading ? <div className="mt-4 flex items-center gap-2 text-sm text-slate-600"><Loader2 className="h-4 w-4 animate-spin" />{copy("يجري حساب التقدير…", "Calculating quote…")}</div> : paidQuote.data ? <div className="mt-4 rounded-2xl border border-violet-100 bg-violet-50 p-4 text-sm text-violet-950"><div className="flex items-center justify-between gap-3"><strong>{copy("إجمالي التقدير", "Estimated total")}</strong><span className="text-lg font-black">{paidQuote.data.totalPriceSar} {copy("ريال", "SAR")}</span></div><p className="mt-2 text-violet-800">{copy(`${paidQuote.data.sizeUnits} وحدة × ${paidQuote.data.unitPriceSar} ريال لكل 10 ميغابايت. لا يؤثر هذا التقدير في طلب التصدير المجاني.`, `${paidQuote.data.sizeUnits} unit(s) × SAR ${paidQuote.data.unitPriceSar} per 10 MB. This quote does not affect the free export request.`)}</p><p className="mt-2 text-xs text-violet-700">{copy("لن يبدأ أي تحصيل من هذا القسم قبل تفعيل حساب التاجر واعتماد المستخدم لمسار الدفع.", "No collection begins here until the merchant account is activated and the payment path is approved.")}</p></div> : <p className="mt-4 text-sm text-slate-600">{copy("يتعذر عرض التقدير لهذه الفئة حاليًا.", "A quote is not available for this category right now.")}</p>}</section>
      <section className="workspace-panel export-status">
        <div className="panel-heading"><div><h2>{copy("حالة ملفات التصدير", "Export file status")}</h2><p>{copy("يظهر هنا كل ملف تم طلب تصديره من مشاريعك.", "Every requested project export appears here.")}</p></div><Button type="button" size="sm" variant="outline" disabled={refreshExports.isPending} onClick={() => refreshExports.mutate()}>{refreshExports.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Clock3 className="h-4 w-4" />}{copy("تحديث الحالة", "Refresh status")}</Button></div>
        {jobs.isLoading ? <LoadingPanel /> : jobs.data?.length ? <div className="export-jobs">{jobs.data.map(job => {
          const statusLabel = exportStatusLabels[job.status][isArabic ? "ar" : "en"];
          return <article key={job.id} className="export-job"><div className="job-file"><FileBox /><div><strong>{job.format.toUpperCase()}</strong><p>{copy("قيد المتابعة", "Being tracked")}</p></div></div><div className="export-job-actions"><span className="status-pill"><Clock3 />{statusLabel}</span>{job.artifactUrl && <a className="artifact-download" href={job.artifactUrl} target="_blank" rel="noreferrer"><Download />{copy("تنزيل", "Download")}</a>}</div></article>;
        })}</div> : <div className="compact-empty"><Download /><strong>{copy("لا توجد ملفات تصدير بعد", "No exports yet")}</strong><p>{copy("اختر مشروعًا وابدأ طلب التصدير؛ ستظهر حالة البناء هنا عند ربط خدمة البناء السحابية.", "Choose a project and request an export; its build status will appear here when the cloud build service is connected.")}</p></div>}
      </section></div>
  </Workspace>;
}
