import type { TemplateCategory, TemplatePageSeed } from "./appBuilderCatalog";

export type PremiumExample = {
  slug: string;
  category: TemplateCategory;
  nameAr: string;
  nameEn: string;
  descriptionAr: string;
  descriptionEn: string;
  accentColor: string;
  iconName: string;
  pages: TemplatePageSeed[];
  components: string[];
};

export const premiumExampleCatalog: PremiumExample[] = [
  { slug: "nova-market", category: "ecommerce", nameAr: "متجر نوفا", nameEn: "Nova Market", descriptionAr: "مثال متجر متكامل للأقسام والعروض والسلة وإدارة الحساب.", descriptionEn: "A complete storefront example with collections, offers, cart, and account management.", accentColor: "#2563EB", iconName: "ShoppingBag", pages: [{ key: "home", titleAr: "الرئيسية", titleEn: "Home" }, { key: "offers", titleAr: "العروض", titleEn: "Offers" }, { key: "catalog", titleAr: "المنتجات", titleEn: "Catalog" }, { key: "cart", titleAr: "السلة", titleEn: "Cart" }, { key: "account", titleAr: "الحساب", titleEn: "Account" }], components: ["Hero offer", "Product grid", "Cart summary"] },
  { slug: "athra-academy", category: "education", nameAr: "أكاديمية إثراء", nameEn: "Athra Academy", descriptionAr: "تجربة تعليمية منظمة للمسارات والدروس والاختبارات والتقدم.", descriptionEn: "An organized learning experience for paths, lessons, quizzes, and progress.", accentColor: "#0E7490", iconName: "GraduationCap", pages: [{ key: "dashboard", titleAr: "لوحة التعلم", titleEn: "Learning dashboard" }, { key: "paths", titleAr: "المسارات", titleEn: "Learning paths" }, { key: "lesson", titleAr: "الدرس", titleEn: "Lesson" }, { key: "quiz", titleAr: "الاختبار", titleEn: "Quiz" }, { key: "progress", titleAr: "التقدم", titleEn: "Progress" }], components: ["Course progress", "Lesson player", "Quiz form"] },
  { slug: "galaxy-challenge", category: "games", nameAr: "تحدي المجرّة", nameEn: "Galaxy Challenge", descriptionAr: "نموذج لعبة يحتوي على بداية ومراحل ومهمات ولوحة نقاط.", descriptionEn: "A game example with a start screen, levels, missions, and score board.", accentColor: "#7C3AED", iconName: "Gamepad2", pages: [{ key: "start", titleAr: "ابدأ اللعب", titleEn: "Start game" }, { key: "levels", titleAr: "المراحل", titleEn: "Levels" }, { key: "mission", titleAr: "المهمة", titleEn: "Mission" }, { key: "scores", titleAr: "النقاط", titleEn: "Scores" }, { key: "profile", titleAr: "الملف", titleEn: "Profile" }], components: ["Level selector", "Mission card", "Score board"] },
  { slug: "naghm-now", category: "music", nameAr: "نغم الآن", nameEn: "Naghm Now", descriptionAr: "مشغل موسيقى حديث للاكتشاف وقوائم التشغيل والألبومات.", descriptionEn: "A modern music player for discovery, playlists, and albums.", accentColor: "#DB2777", iconName: "Music2", pages: [{ key: "discover", titleAr: "اكتشف", titleEn: "Discover" }, { key: "now-playing", titleAr: "يعمل الآن", titleEn: "Now playing" }, { key: "playlists", titleAr: "قوائم التشغيل", titleEn: "Playlists" }, { key: "albums", titleAr: "الألبومات", titleEn: "Albums" }, { key: "library", titleAr: "مكتبتي", titleEn: "My library" }], components: ["Track player", "Playlist list", "Album carousel"] },
  { slug: "madar-podcast", category: "podcasts", nameAr: "بودكاست مدار", nameEn: "Madar Podcast", descriptionAr: "منصة حلقات صوتية مقترحة وقنوات ومتابعة الاستماع.", descriptionEn: "An audio platform for suggested episodes, channels, and listening progress.", accentColor: "#9333EA", iconName: "Mic2", pages: [{ key: "featured", titleAr: "الحلقات المميزة", titleEn: "Featured episodes" }, { key: "episode", titleAr: "الحلقة", titleEn: "Episode" }, { key: "channels", titleAr: "القنوات", titleEn: "Channels" }, { key: "saved", titleAr: "المحفوظات", titleEn: "Saved" }, { key: "profile", titleAr: "الملف", titleEn: "Profile" }], components: ["Episode player", "Channel list", "Saved queue"] },
  { slug: "studio-watch", category: "movies", nameAr: "شاهد ستوديو", nameEn: "Studio Watch", descriptionAr: "مكتبة عرض للأفلام والمسلسلات والقوائم والمواسم.", descriptionEn: "A watch library for movies, shows, watchlists, and seasons.", accentColor: "#EA580C", iconName: "Clapperboard", pages: [{ key: "featured", titleAr: "المختارات", titleEn: "Featured" }, { key: "movies", titleAr: "الأفلام", titleEn: "Movies" }, { key: "shows", titleAr: "المسلسلات", titleEn: "Shows" }, { key: "details", titleAr: "التفاصيل", titleEn: "Details" }, { key: "watchlist", titleAr: "قائمتي", titleEn: "Watchlist" }], components: ["Featured banner", "Movie grid", "Season list"] },
  { slug: "khidmati-pro", category: "services", nameAr: "خدماتي برو", nameEn: "Khidmati Pro", descriptionAr: "مثال لإدارة الخدمات والحجوزات والعملاء والمواعيد.", descriptionEn: "A service example for managing offers, bookings, clients, and appointments.", accentColor: "#059669", iconName: "BriefcaseBusiness", pages: [{ key: "services", titleAr: "الخدمات", titleEn: "Services" }, { key: "booking", titleAr: "الحجز", titleEn: "Book service" }, { key: "schedule", titleAr: "المواعيد", titleEn: "Schedule" }, { key: "clients", titleAr: "العملاء", titleEn: "Clients" }, { key: "account", titleAr: "الحساب", titleEn: "Account" }], components: ["Service cards", "Booking form", "Schedule list"] },
];
