import { CheckCircle2, Crown, Layers3 } from "lucide-react";
import { paidExportPricePerTenMbSar } from "@shared/exportPricing";
import { templateCategories, type TemplateCategory } from "@shared/appBuilderCatalog";
import "./export-plans.css";

const labels: Record<TemplateCategory, { ar: string; en: string }> = {
  ecommerce: { ar: "متجر إلكتروني", en: "E-commerce" }, education: { ar: "تطبيق تعليمي", en: "Education" }, games: { ar: "تطبيق ألعاب", en: "Games" }, music: { ar: "تطبيق موسيقى", en: "Music" }, podcasts: { ar: "تطبيق بودكاست", en: "Podcasts" }, movies: { ar: "أفلام ومسلسلات", en: "Movies & shows" }, services: { ar: "تطبيق خدمات", en: "Services" }, books: { ar: "تطبيق كتب", en: "Books App" },
};

export function ExportPlansPanel({ isArabic }: { isArabic: boolean }) {
  const text = (ar: string, en: string) => isArabic ? ar : en;
  return <section className="export-plans-panel" aria-labelledby="export-plans-title"><div className="export-plans-heading"><p className="section-kicker">{text("تسعير التصدير", "EXPORT PRICING")}</p><h2 id="export-plans-title">{text("تصدير مدفوع لكل مشروع", "Paid export for every project")}</h2><p>{text("كل القوالب تستخدم التسعير بحسب الفئة وحجم الملف. يعرض الجدول السعر لكل 10 ميغابايت، بينما تُحسب الفاتورة نسبيًا لكل ميغابايت بسعر يعادل عُشر القيمة.", "Every template uses category- and file-size-based pricing. The table shows each 10 MB rate, while invoices are calculated proportionally per MB at one tenth of that rate.")}</p></div><div className="export-plan-cards"><article className="export-plan-card paid"><div className="export-plan-icon"><Crown /></div><p className="export-plan-label">{text("التصدير المدفوع", "PAID EXPORT")}</p><h3>{text("يدفع لكل طلب تصدير", "Pay per export request")}</h3><p>{text("راجع التقدير قبل فتح فاتورة الدفع. يبدأ البناء بعد تحقق الخادم من سداد الفاتورة.", "Review the quote before opening checkout. The build begins after the server verifies invoice payment.")}</p><ul><li><CheckCircle2 />{text("القوالب الأساسية الثمانية", "All eight base templates")}</li><li><CheckCircle2 />{text("الحساب لكل ميغابايت", "Billed per MB")}</li><li><CheckCircle2 />{text("تنزيل محمي بعد الدفع والبناء", "Protected download after payment and build")}</li></ul></article></div><div className="paid-price-table"><div className="paid-price-heading"><Layers3 /><div><h3>{text("أسعار التصدير", "Export pricing")}</h3><p>{text("السعر المعروض لكل 10 ميغابايت؛ الفاتورة تحسب عُشر السعر لكل ميغابايت.", "Rates are shown per 10 MB; each MB is billed at one tenth of the displayed rate.")}</p></div></div><div className="paid-price-grid">{templateCategories.map(category => <div className="paid-price-row" key={category}><span>{labels[category][isArabic ? "ar" : "en"]}</span><strong>{isArabic ? `${paidExportPricePerTenMbSar[category]} ريال` : `SAR ${paidExportPricePerTenMbSar[category]}`}</strong></div>)}</div></div></section>;
}
