import { CheckCircle2, Crown, Gift, Layers3 } from "lucide-react";
import { hasPaidExportPrice, paidExportPricePerTenMbSar } from "@shared/exportPricing";
import { templateCategories, type TemplateCategory } from "@shared/appBuilderCatalog";
import "./export-plans.css";

const labels: Record<TemplateCategory, { ar: string; en: string }> = {
  ecommerce: { ar: "متجر إلكتروني", en: "E-commerce" }, education: { ar: "تطبيق تعليمي", en: "Education" }, games: { ar: "تطبيق ألعاب", en: "Games" }, music: { ar: "تطبيق موسيقى", en: "Music" }, podcasts: { ar: "تطبيق بودكاست", en: "Podcasts" }, movies: { ar: "أفلام ومسلسلات", en: "Movies & shows" }, services: { ar: "تطبيق خدمات", en: "Services" }, books: { ar: "تطبيق كتب", en: "Books App" },
};

export function ExportPlansPanel({ isArabic }: { isArabic: boolean }) {
  const text = (ar: string, en: string) => isArabic ? ar : en;
  const priceText = (category: TemplateCategory) => {
    if (!hasPaidExportPrice(category)) return text("يتطلب تحديد السعر", "Price pending");
    const price = paidExportPricePerTenMbSar[category];
    return isArabic ? `${price} ريال` : `SAR ${price}`;
  };
  return <section className="export-plans-panel" aria-labelledby="export-plans-title"><div className="export-plans-heading"><p className="section-kicker">{text("نموذجا التصدير", "EXPORT MODELS")}</p><h2 id="export-plans-title">{text("اختر المسار المناسب لكل مشروع", "Choose the right path for each project")}</h2><p>{text("ابدأ مجانًا، أو اختر التصدير المدفوع عندما تحتاج نموذجًا تطبيقيًا مكتملًا ومزايا حصرية.", "Start free, or choose paid export when you need a complete app example and exclusive benefits.")}</p></div><div className="export-plan-cards"><article className="export-plan-card free"><div className="export-plan-icon"><Gift /></div><p className="export-plan-label">{text("النسخة المجانية", "FREE EDITION")}</p><h3>{text("مجانية بالكامل", "Completely free")}</h3><p>{text("أنشئ مشاريعك من القوالب الأساسية واطلب التصدير المجاني مباشرة من مساحة العمل.", "Create projects from the base templates and place free export requests directly from your workspace.")}</p><ul><li><CheckCircle2 />{text("القوالب الأساسية الثمانية", "Eight base templates")}</li><li><CheckCircle2 />{text("المحرر والمعاينة وإدارة المشاريع", "Editor, preview, and project management")}</li><li><CheckCircle2 />{text("لا فاتورة ولا بوابة دفع", "No invoice or payment gateway")}</li></ul></article><article className="export-plan-card paid"><div className="export-plan-icon"><Crown /></div><p className="export-plan-label">{text("التصدير المدفوع", "PAID EXPORT")}</p><h3>{text("يدفع لكل طلب تصدير", "Pay per export request")}</h3><p>{text("يتضمن الوصول إلى أمثلة التطبيقات المكتملة الحصرية، ويُحسب السعر بحسب فئة القالب وحجم الملف.", "Includes access to exclusive complete app examples, priced by template category and file size.")}</p><ul><li><CheckCircle2 />{text("أمثلة تطبيقات مكتملة للفئات المسعّرة", "Complete app examples for priced categories")}</li><li><CheckCircle2 />{text("الحساب لكل 10 ميغابايت", "Billed per 10 MB")}</li><li><CheckCircle2 />{text("التحصيل لا يبدأ قبل ضبط مزود الدفع", "Collection starts only after payment-provider setup")}</li></ul></article></div><div className="paid-price-table"><div className="paid-price-heading"><Layers3 /><div><h3>{text("أسعار التصدير المدفوع", "Paid export pricing")}</h3><p>{text("السعر لكل 10 ميغابايت؛ يُقرّب الحجم دائمًا إلى الوحدة الأعلى.", "Price per 10 MB; file size always rounds up to the next unit.")}</p></div></div><div className="paid-price-grid">{templateCategories.map(category => <div className="paid-price-row" key={category}><span>{labels[category][isArabic ? "ar" : "en"]}</span><strong>{priceText(category)}</strong></div>)}</div></div></section>;
}
